export const APP_TYPE_PROPERTY_LIST_MODULE_FIELD = {
  Action: 'Action',
  'App code': 'App code',
  'App name': 'App name',
  'Sync location': 'Sync location',
  'Data life span': 'Data life span',
  'File validity': 'File validity',
  'Auto de-active': 'Auto de-active',
  'Auto purge': 'Auto purge',
  Network: 'Network',
  'Download limit': 'Download limit',
  'USB path': 'USB path',
  'Auto flush': 'Auto flush',
  'Enable vessel field inspection': 'Enable vessel field inspection',
  'Android app version': 'Android app version',
  'IOS app version': 'IOS app version',
  'Windows app version': 'Windows app version',
  'Created by company': 'Created by company',
};

export const APP_TYPE_PROPERTY_DETAIL_MODULE_FIELD = {
  'App code': 'App code',
  'App name': 'App name',
  'Sync location': 'Sync location',
  'Data life span [month(s)]': 'Data life span [month(s)]',
  'File validity [day(s)]': 'File validity [day(s)]',
  'Auto de-active [day(s)]': 'Auto de-active [day(s)]',
  'Auto purge [day(s)]': 'Auto purge [day(s)]',
  Network: 'Network',
  'Mobile data': 'Mobile data',
  Wifi: 'Wifi',
  Both: 'Both',
  'Download limit [MB]': 'Download limit [MB]',
  'USB path': 'USB path',
  'Auto flush': 'Auto flush',
  'Enable vessel field inspection': 'Enable vessel field inspection',
  'Android app version': 'Android app version',
  'IOS app version': 'IOS app version',
  'Windows app version': 'Windows app version',
  'of 10 characters': 'of 10 characters',
  'of 20 characters': 'of 20 characters',
  'of 128 characters': 'of 128 characters',
  Cancel: 'Cancel',
  Save: 'Save',
  'Enter app name': 'Enter app name',
  'Enter USB path': 'Enter USB path',
  'Enter auto purge': 'Enter auto purge',
  'Enter file validity': 'Enter file validity',
  'Enter auto de-active': 'Enter auto de-active',
  'Enter download limit': 'Enter download limit',
  'Enter app code': 'Enter app code',
  'Enter sync location': 'Enter sync location',
  'Enter android app version': 'Enter android app version',
  'Enter IOS app version': 'Enter IOS app version',
  'Enter windows app version': 'Enter windows app version',
  'App type property': 'App type property',
  Back: 'Back',
  Edit: 'Edit',
  'App type property information': 'App type property information',
  'Confirmation?': 'Confirmation?',
  'Are you sure you want to proceed with this action?':
    'Are you sure you want to proceed with this action?',
  'Auto purge must not be greater than 30000':
    'Auto purge must not be greater than 30000',
  'File validity must not be greater than 30000':
    'File validity must not be greater than 30000',
  'Data life span must not be greater than 30000':
    'Data life span must not be greater than 30000',
  'Auto de-active must not be greater than 30000':
    'Auto de-active must not be greater than 30000',
  'Download limit must not be greater than 30000':
    'Download limit must not be greater than 30000',
};
