export const AUDIT_CHECKLIST_TEMPLATE_DYNAMIC_LIST_FIELDS = {
  'Checklist code': 'Checklist code',
  'Checklist name': 'Checklist name',
  'Revision number': 'Revision number',
  Entity: 'Entity',
  'Revision date': 'Revision date',
  Status: 'Status',
  'Checklist type': 'Checklist type',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Created by company': 'Created by company',
  'Revoke/ Recall': 'Revoke/ Recall',
  'Create New': 'Create New',
  Action: 'Action',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  'Delete?': 'Delete?',
  Delete: 'Delete',
  Cancel: 'Cancel',
  'On revoking, the task gets open to any user in this stage. Do you want to proceed?':
    'On revoking, the task gets open to any user in this stage. Do you want to proceed?',
  'On recall, your submitted task will be reverted to you if no one has claimed yet. Do you want to proceed?':
    'On recall, your submitted task will be reverted to you if no one has claimed yet. Do you want to proceed?',
  Yes: 'Yes',
  Confirmation: 'Confirmation',
};

export const AUDIT_CHECKLIST_TEMPLATE_DYNAMIC_DETAIL_FIELDS = {
  'General information': 'General information',
  'Question list': 'Question list',
  'Workflow progress': 'Workflow progress',
  'Checklist preview': 'Checklist preview',
  'Inspection checklist template': 'Inspection checklist template',
  'Checklist code': 'Checklist code',
  Hint: 'Hint',
  Accept: 'Accept',
  generalInformation: {
    Entity: 'Entity',
    'Checklist code': 'Checklist code',
    'Checklist type': 'Checklist type',
    'Checklist name': 'Checklist name',
    'Revision number': 'Revision number',
    'Revision date': 'Revision date',
    'Published date': 'Published date',
    'Checklist validity period': 'Checklist validity period',
    'User name': 'User name',
    'Inspection module': 'Inspection module',
    'Visit type': 'Visit type',
    Selected: 'Selected',
    'Updated date': 'Updated date',
    'User history section': 'User history section',
    'Job title': 'Job title',
    Port: 'Port',
    Sailing: 'Sailing',
    Inspection: 'Inspection',
    'Inspection report': 'Inspection report',
    'Inspection finding report': 'Inspection finding report',
    'Report of finding': 'Report of finding',
    'Enter checklist name': 'Enter checklist name',
    'Enter revision number': 'Enter revision number',
    'Please select': 'Please select',
    'References & Category': 'References & Category',
    'Select all': 'Select all',
    Cancel: 'Cancel',
    Save: 'Save',
    'Save & New': 'Save & New',
    Next: 'Next',
    'S.No': 'S.No',
    Status: 'Status',
    'User Name': 'User Name',
    'Job Title': 'Job Title',
    'Updated Date': 'Updated Date',
    Comment: 'Comment',
    Action: 'Action',
    Checkbox: 'Checkbox',
    'References & Category field names': 'References & Category field names',
  },
  questionList: {
    'Minimum picture required must greater than 0 if Evidence picture required is Yes':
      'Minimum picture required must greater than 0 if Evidence picture required is Yes',
    'Must be between 2 and 2000 characters':
      'Must be between 2 and 2000 characters',
    Category: 'Category',
    'Invalid amount': 'Invalid amount',
    'Section information': 'Section information',
    'Question details': 'Question details',
    'Must have at least 2 options': 'Must have at least 2 options',
    'Must have at least 2 answers': 'Must have at least 2 answers',
    'Please select at least 1 option after choosing specific':
      'Please select at least 1 option after choosing specific',
    'Each value in answer options must be longer than or equal to 1 characters':
      'Each value in answer options must be longer than or equal to 1 characters',
    "Question's option must not contains duplicate value":
      "Question's option must not contains duplicate value",
    'Question information': 'Question information',
    Verification: 'Verification',
    'References & Category': 'References & Category',
    'Value information': 'Value information',
    'Section Information': 'Section Information',
    'Question list': 'Question list',
    'To change question order, please drag!':
      'To change question order, please drag!',
    'View full question details': 'View full question details',
    'Add question': 'Add question',
    'S.No': 'S.No',
    'Question code': 'Question code',
    'Question name': 'Question name',
    'Question type': 'Question type',
    'Allow values': 'Allow values',
    Hint: 'Hint',
    'Mandatory remarks': 'Mandatory remarks',
    'Min picture required': 'Min picture required',
    'Rating Criteria': 'Rating Criteria',
    Topic: 'Topic',
    Evidence: 'Evidence',
    'Row No': 'Row No',
    Error: 'Error',
    Close: 'Close',
    'Uploaded fail': 'Uploaded fail',
    Reviewer: 'Reviewer',
    Approver: 'Approver',
    'Are you sure you want to': 'Are you sure you want to',
    'User assignment': 'User assignment',
    'Answer option': 'Answer option',
    Value: 'Value',
    "We are processing your file and will notify you after it's done":
      "We are processing your file and will notify you after it's done",
    'Importing will continue even if you leave the page':
      'Importing will continue even if you leave the page',
    Location: 'Location',
    'Vessel type': 'Vessel type',
    CDI: 'CDI',
    VIQ: 'VIQ',
    'Charter/ Owner': 'Charter/ Owner',
    'Main category': 'Main category',
    'Second category': 'Second category',
    'Shore rank': 'Shore rank',
    'Shore department': 'Shore department',
    'Ship department': 'Ship department',
    'Third category': 'Third category',
    'Enter question code': 'Enter question code',
    'Add findings': 'Add findings',
    Question: 'Question',
    'Add multiple': 'Add multiple',
    'Enter question': 'Enter question',
    Mandatory: 'Mandatory',
    'Mandatory remark for findings': 'Mandatory remark for findings',
    All: 'All',
    Specific: 'Specific',
    'Evidence picture required': 'Evidence picture required',
    'Minimum picture required': 'Minimum picture required',
    'Enter minimum picture required': 'Enter minimum picture required',
    'Selected Topic': 'Selected Topic',
    'Select all': 'Select all',
    Confirm: 'Confirm',
    'Please select': 'Please select',
    'Enter rating criteria': 'Enter rating criteria',
    'Rating criteria': 'Rating criteria',
    'Enter hint': 'Enter hint',
    'General information': 'General information',
    'Selected group': 'Selected group',
    Department: 'Department',
    'Charter owner': 'Charter owner',
    'Selected VIQ': 'Selected VIQ',
    'Selected Charter/ Owner': 'Selected Charter/ Owner',
    Reg: 'Reg',
    'Enter reg': 'Enter reg',
    'Selected main categor': 'Selected main categor',
    'Selected second category': 'Selected second category',
    'Selected third category': 'Selected third category',
    'Selected ship department': 'Selected ship department',
    'Ship rank': 'Ship rank',
    'Selected ship rank': 'Selected ship rank',
    'Selected shore department': 'Selected shore department',
    'Selected shore rank': 'Selected shore rank',
    High: 'High',
    Medium: 'Medium',
    Low: 'Low',
    'Potential risk': 'Potential risk',
    'Enter infor': 'Enter infor',
    'View value': 'View value',
    'Edit value': 'Edit value',
    'Add value': 'Add value',
    Criticality: 'Criticality',
    Infor: 'Infor',
    Attach: 'Attach',
    'Vessel code': 'Vessel code',
    'Vessel name': 'Vessel name',
    'Ref.No': 'Ref.No',
    Entity: 'Entity',
    'Inspection number': 'Inspection number',
    'Inspection type': 'Inspection type',
    'Findings comment': 'Findings comment',
    'Nature of finding': 'Nature of finding',
    'Checklist code': 'Checklist code',
    'Module id': 'Module id',
    'Module name': 'Module name',
  },
};
