export const CAR_CAP_DYNAMIC_FIELDS = {
  'Corrective action request': 'Corrective action request',
  CAR: 'CAR',
  CAP: 'CAP',
  'CAP review': 'CAP review',
  Verification: 'Verification',
  'CAR S.No': 'CAR S.No',
  'CAR Ref.Id': 'CAR Ref.Id',
  'Select findings': 'Select findings',
  Findings: 'Findings',
  Search: 'Search',
  'Clear all': 'Clear all',
  'S.No': 'S.No',
  'Reference number': 'Reference number',
  'Inspection type': 'Inspection type',
  'Finding comments': 'Finding comments',
  'Total size': 'Total size',
  'Finding remarks': 'Finding remarks',
  'Finding type': 'Finding type',
  'CAP status': 'CAP status',
  Date: 'Date',
  'CAR (Corrective action request)': 'CAR (Corrective action request)',
  'Enter CAR (Corrective action request)':
    'Enter CAR (Corrective action request)',
  'CAP target period': 'CAP target period',
  'Enter target period': 'Enter target period',
  'CAP target end date': 'CAP target end date',
  'CAR attachment': 'CAR attachment',
  'Corrective action plan': 'Corrective action plan',
  'CAP (Corrective action plan)': 'CAP (Corrective action plan)',
  'Root cause': 'Root cause',
  'Enter preventive action': 'Enter preventive action',
  'Enter comment': 'Enter comment',
  Comment: 'Comment',
  'Enter CAP (Corrective action plan)': 'Enter CAP (Corrective action plan)',
  'Enter root cause': 'Enter root cause',
  'Please select': 'Please select',
  'Estimated closure date': 'Estimated closure date',
  'PIC name': 'PIC name',
  'Enter pic name': 'Enter pic name',
  'Actual closure date': 'Actual closure date',
  'Preventive action': 'Preventive action',
  'CAP comment': 'CAP comment',
  'Verification type': 'Verification type',
  'Verification needed': 'Verification needed',
  'Next inspection': 'Next inspection',
  'Additional inspection': 'Additional inspection',
  Manually: 'Manually',
  'Verification status': 'Verification status',
  Pending: 'Pending',
  Holding: 'Holding',
  'Verified and closed': 'Verified and closed',
  'Overriding closure': 'Overriding closure',
  Reason: 'Reason',
  'Enter reason': 'Enter reason',
  'Verified date': 'Verified date',
  'Verified by': 'Verified by',
  'Verification attachment': 'Verification attachment',
  'This field is required': 'This field is required',
  'CAR Ref.ID': 'CAR Ref.ID',
  Add: 'Add',
  Action: 'Action',
  'File name': 'File name',
  'File size': 'File size',
  'Uploaded date time': 'Uploaded date time',
  'Uploaded by': 'Uploaded by',
  'Commented by': 'Commented by',
  'Commented date': 'Commented date',
  'Add comment': 'Add comment',
  'Inspection ref id': 'Inspection ref id',
  'Planned from date': 'Planned from date',
  'Planned to date': 'Planned to date',
  'Inspector name': 'Inspector name',
  'Lead inspector name': 'Lead inspector name',
  'From port': 'From port',
  'To port': 'To port',
  'Inspection plan': 'Inspection plan',
};
