export const CHARTER_OWNER_DYNAMIC_LIST_FIELDS = {
  Action: 'Action',
  'Charter/Owner name': 'Charter/Owner name',
  'Charter/Owner code': 'Charter/Owner code',
  Description: 'Description',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  Status: 'Status',
  'Created by company': 'Created by company',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  Cancel: 'Cancel',
  Delete: 'Delete',
  'Create New': 'Create New',
  'Charter/Owner': 'Charter/Owner',
};

export const CHARTER_OWNER_DYNAMIC_DETAIL_FIELDS = {
  'Charter/Owner Name': 'Charter/Owner Name',
  'Charter/Owner Code': 'Charter/Owner Code',
  Description: 'Description',
  Status: 'Status',
  'Enter charter/owner code': 'Enter charter/owner code',
  'Enter charter/owner name': 'Enter charter/owner name',
  'Enter description': 'Enter description',
  Active: 'Active',
  Inactive: 'Inactive',
  'Charter/Owner information': 'Charter/Owner information',
  'Charter/Owner code': 'Charter/Owner code',
  'Charter/Owner name': 'Charter/Owner name',
  Cancel: 'Cancel',
  Delete: 'Delete',
  Back: 'Back',
  Edit: 'Edit',
  Save: 'Save',
  'Save & New': 'Save & New',
  'This field is required': 'This field is required',
  'The charter/owner code is existed': 'The charter/owner code is existed',
  'The charter/owner name is existed': 'The charter/owner name is existed',
};
