export const COMMON_DYNAMIC_FIELDS = {
  Action: 'Action',
  Status: 'Status',
  Code: 'Code',
  'Enter area': 'Enter area',
  'Enter auditee': 'Enter auditee',
  'Inspection time table': 'Inspection time table',
  Name: 'Name',
  Back: 'Back',
  Enter: 'Enter',
  Complete: 'Complete',
  'Please add value for answer option': 'Please add value for answer option',
  'Current date': 'Current date',
  'File name': 'File name',
  'File size': 'File size',
  'Create at': 'Create at',
  Month: 'Month',
  'Enter template name': 'Enter template name',
  'Enter comment': 'Enter comment',
  'Template name': 'Template name',
  Value: 'Value',
  Week: 'Week',
  'Workflow progress': 'Workflow progress',
  Reviewer: 'Reviewer',
  Verify: 'Verify',
  Day: 'Day',
  Reassign: 'Reassign',
  'Close out': 'Close out',
  TEMPLATES: 'TEMPLATES',
  Approver: 'Approver',
  Upload: 'Upload',
  All: 'All',
  Vessel: 'Vessel',
  Update: 'Update',
  Office: 'Office',
  'List of templates': 'List of templates',
  'Enter bcc': 'Enter bcc',
  'Delete template': 'Delete template',
  'Enter action': 'Enter action',
  Group: 'Group',
  'Vessel type': 'Vessel type',
  'Start date': 'Start date',
  'Vetting management risk score': 'Vetting management risk score',
  'Enter memo': 'Enter memo',
  'Date to': 'Date to',
  'Date from': 'Date from',
  'Port type': 'Port type',
  Scope: 'Scope',
  'User assignment': 'User assignment',
  Country: 'Country',
  'Field type': 'Field type',
  'Total findings': 'Total findings',
  'VIQ vessel type': 'VIQ vessel type',
  Original: 'Original',
  Adjusted: 'Adjusted',
  'Select date': 'Select date',
  Role: 'Role',
  'First reviewer': 'First reviewer',
  'Second reviewer': 'Second reviewer',
  'Total weighted score': 'Total weighted score',
  'Third reviewer': 'Third reviewer',
  'Fourth reviewer': 'Fourth reviewer',
  'Fifth reviewer': 'Fifth reviewer',
  Edit: 'Edit',
  'Are you sure you want to': 'Are you sure you want to',
  'are you sure you want to': 'are you sure you want to',

  'Business division': 'Business division',
  Company: 'Company',
  Description: 'Description',
  'Owner/Manager': 'Owner/Manager',
  Acceptor: 'Acceptor',
  'Save & New': 'Save & New',
  'Select all': 'Select all',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  'Cancel?': 'Cancel?',
  'Are you sure you want to proceed with this action?':
    'Are you sure you want to proceed with this action?',
  Confirm: 'Confirm',
  Add: 'Add',
  Delete: 'Delete',
  Cancel: 'Cancel',
  Preview: 'Preview',
  Save: 'Save',
  Submit: 'Submit',
  Approve: 'Approve',
  Reject: 'Reject',
  Attach: 'Attach',
  'User name': 'User name',
  'Job title': 'Job title',
  Selected: 'Selected',
  'Please selected': 'Please selected',
  'Choose template': 'Choose template',
  '5 / page': '5 / page',
  '10 / page': '10 / page',
  '20 / page': '20 / page',
  '35 / page': '35 / page',
  '50 / page': '50 / page',
  '100 / page': '100 / page',
  'View more': 'View more',
  'Yet to start': 'Yet to start',
  'In progress': 'In progress',
  Completed: 'Completed',
  'Total Records': 'Total Records',
  'Please select': 'Please select',
  'This field is required': 'This field is required',
  'The template name is existed': 'The template name is existed',
  'The role name is existed': 'The role name is existed',
  'Subject must be smaller than 500': 'Subject must be smaller than 500',
  'New mail': 'New mail',
  'Mail template': 'Mail template',
  From: 'From',
  To: 'To',
  Cc: 'Cc',
  Bcc: 'Bcc',
  Send: 'Send',
  'Save as draft': 'Save as draft',
  'Enter from': 'Enter from',
  'Enter to': 'Enter to',
  'Enter cc': 'Enter cc',

  'The email is invalid, please click the verification link in verification request email to verify it':
    'The email is invalid, please click the verification link in verification request email to verify it',
  Subject: 'Subject',
  'Please enter to email to add the mail address':
    'Please enter to email to add the mail address',
  'Please enter cc email to add the mail address':
    'Please enter cc email to add the mail address',
  'Please enter bcc email to add the mail address':
    'Please enter bcc email to add the mail address',
  Body: 'Body',
  Select: 'Select',
  'Clear all': 'Clear all',
  Search: 'Search',
  Active: 'Active',
  Inactive: 'Inactive',
  'Create New': 'Create New',
  'No data': 'No data',
  Entity: 'Entity',
  Export: 'Export',
  'Send mail': 'Send mail',
  Review: 'Review',
  'Corrective action request': 'Corrective action request',
  Deny: 'Deny',
  Accept: 'Accept',
  'Confirmation?': 'Confirmation?',
  'Number should be more than 0': 'Number should be more than 0',
  Draft: 'Draft',
  Submitted: 'Submitted',
  Reviewed: 'Reviewed',
  Approved: 'Approved',
  Cancelled: 'Cancelled',
  'Choose Template': 'Choose Template',
  'Must be at least 2 characters': 'Must be at least 2 characters',
  'Download template': 'Download template',
  'Import excel': 'Import excel',
  'Export excel': 'Export excel',
  'Select icon': 'Select icon',
  week: 'week',
  month: 'month',
  months: 'months',
  year: 'year',
  Questions: 'Questions',
  Question: 'Question',
  Confirmation: 'Confirmation',
  'Enter are you sure you want to review?':
    'Enter are you sure you want to review?',
  'Enter are you sure you want to close out?':
    'Enter are you sure you want to close out?',
  'Enter are you sure you want to reassign?':
    'Enter are you sure you want to reassign?',
  'Confirm deletion': 'Confirm deletion',
  'The references & category will be removed in all questions':
    'The references & category will be removed in all questions',
  'Are you sure you want to proceed with this action? your change here will impact the references & category in all questions':
    'Are you sure you want to proceed with this action? your change here will impact the references & category in all questions',
  Next: 'Next',
  in: 'in',
  Present: 'Present',
  Yes: 'Yes',
  No: 'No',
  Experience: 'Experience',
  'Add remarks': 'Add remarks',
  Remarks: 'Remarks',
  'Enter remarks': 'Enter remarks',
  preview: 'preview',
  'choose-template': 'choose-template',
  accept: 'accept',
  approve: 'approve',
  reject: 'reject',
  review: 'review',
  cancel: 'cancel',
  edit: 'edit',
  delete: 'delete',
  export: 'export',
  back: 'back',
  reassign: 'reassign',
  closeout: 'closeout',
  'Enter confirmation': 'Enter confirmation',
};

export const AG_DYNAMIC_FIELDS = {
  // Set Filter
  'Save template': 'Save template',
  'Save as template': 'Save as template',
  'Delete template': 'Delete template',
  'Global template': 'Global template',
  'Distinct filter': 'Distinct filter',
  'Condition filter': 'Condition filter',
  'Multiple filter': 'Multiple filter',
  Reset: 'Reset',
  Excel: 'Excel',
  CSV: 'CSV',
  'Full screen': 'Full screen',
  selectAll: '(Select All)',
  selectAllSearchResults: '(Select All Search Results)',
  searchOoo: 'Search...',
  blanks: '(Blanks)',
  noMatches: 'No matches',

  // Number Filter & Text Filter
  filterOoo: 'Filter...',
  equals: 'Equals',
  notEqual: 'Not equal',
  blank: 'Blank',
  notBlank: 'Not blank',
  empty: 'Choose One',

  // Number Filter
  lessThan: 'Less than',
  greaterThan: 'Greater than',
  lessThanOrEqual: 'Less than or equal',
  greaterThanOrEqual: 'Greater than or equal',
  inRange: 'In range',
  inRangeStart: 'from',
  inRangeEnd: 'to',

  // Text Filter
  contains: 'Contains',
  notContains: 'Not contains',
  startsWith: 'Starts with',
  endsWith: 'Ends with',

  // Date Filter
  dateFormatOoo: 'yyyy-mm-dd',

  // Filter Conditions
  andCondition: 'AND',
  orCondition: 'OR',

  // Filter Buttons
  applyFilter: 'Apply',
  resetFilter: 'Reset',
  clearFilter: 'Clear',
  cancelFilter: 'Cancel',

  // Filter Titles
  textFilter: 'Text Filter',
  numberFilter: 'Number Filter',
  dateFilter: 'Date Filter',
  setFilter: 'Set Filter',

  // Side Bar
  columns: 'Columns',
  filters: 'Filters',

  // columns tool panel
  pivotMode: 'Pivot Mode',
  groups: 'Row Groups',
  rowGroupColumnsEmptyMessage: 'Drag here to set row groups',
  values: 'Values',
  valueColumnsEmptyMessage: 'Drag here to aggregate',
  pivots: 'Column Labels',
  pivotColumnsEmptyMessage: 'Drag here to set column labels',

  // Header of the Default Group Column
  group: 'Group',

  // Row Drag
  rowDragRow: 'row',
  rowDragRows: 'rows',

  // Other
  loadingOoo: 'Loading...',
  noRowsToShow: 'No Rows To Show',
  enabled: 'Enabled',

  // Menu
  pinColumn: 'Pin Column',
  pinLeft: 'Pin Left',
  pinRight: 'Pin Right',
  noPin: 'No Pin',
  valueAggregation: 'Value Aggregation',
  autosizeThiscolumn: 'Autosize This Column',
  autosizeAllColumns: 'Autosize All Columns',
  groupBy: 'Group by',
  ungroupBy: 'Un-Group by',
  resetColumns: 'Reset Columns',
  expandAll: 'Expand All',
  collapseAll: 'Close All',
  copy: 'Copy',
  ctrlC: 'Ctrl+C',
  copyWithHeaders: 'Copy With Headers',
  copyWithGroupHeaders: 'Copy with Group Headers',
  paste: 'Paste',
  ctrlV: 'Ctrl+V',
  export: 'Export',
  csvExport: 'CSV Export',
  excelExport: 'Excel Export',

  // Enterprise Menu Aggregation and Status Bar
  sum: 'Sum',
  min: 'Min',
  max: 'Max',
  none: 'None',
  count: 'Count',
  avg: 'Average',
  filteredRows: 'Filtered',
  selectedRows: 'Selected',
  totalRows: 'Total Rows',
  totalAndFilteredRows: 'Rows',
  more: 'More',
  to: 'to',
  of: 'of',
  page: 'Page',
  nextPage: 'Next Page',
  lastPage: 'Last Page',
  firstPage: 'First Page',
  previousPage: 'Previous Page',

  // Pivoting
  pivotColumnGroupTotals: 'Total',

  // Enterprise Menu (Charts)
  pivotChartAndPivotMode: 'Pivot Chart & Pivot Mode',
  pivotChart: 'Pivot Chart',
  chartRange: 'Chart Range',

  columnChart: 'Column',
  groupedColumn: 'Grouped',
  stackedColumn: 'Stacked',
  normalizedColumn: '100% Stacked',

  barChart: 'Bar',
  groupedBar: 'Grouped',
  stackedBar: 'Stacked',
  normalizedBar: '100% Stacked',

  pieChart: 'Pie',
  pie: 'Pie',
  doughnut: 'Doughnut',

  line: 'Line',

  xyChart: 'X Y (Scatter)',
  scatter: 'Scatter',
  bubble: 'Bubble',

  areaChart: 'Area',
  area: 'Area',
  stackedArea: 'Stacked',
  normalizedArea: '100% Stacked',

  histogramChart: 'Histogram',
  histogramFrequency: 'Frequency',

  combinationChart: 'Combination',
  columnLineCombo: 'Column & Line',
  AreaColumnCombo: 'Area & Column',

  // Charts
  pivotChartTitle: 'Pivot Chart',
  rangeChartTitle: 'Range Chart',
  settings: 'Settings',
  data: 'Data',
  format: 'Format',
  categories: 'Categories',
  defaultCategory: '(None)',
  series: 'Series',
  xyValues: 'X Y Values',
  paired: 'Paired Mode',
  axis: 'Axis',
  navigator: 'Navigator',
  color: 'Color',
  thickness: 'Thickness',
  xType: 'X Type',
  automatic: 'Automatic',
  category: 'Category',
  number: 'Number',
  time: 'Time',
  autoRotate: 'Auto Rotate',
  xRotation: 'X Rotation',
  yRotation: 'Y Rotation',
  ticks: 'Ticks',
  width: 'Width',
  height: 'Height',
  length: 'Length',
  padding: 'Padding',
  spacing: 'Spacing',
  chart: 'Chart',
  title: 'Title',
  titlePlaceholder: 'Chart title - double click to edit',
  background: 'Background',
  font: 'Font',
  top: 'Top',
  right: 'Right',
  bottom: 'Bottom',
  left: 'Left',
  labels: 'Labels',
  size: 'Size',
  minSize: 'Minimum Size',
  maxSize: 'Maximum Size',
  legend: 'Legend',
  position: 'Position',
  markerSize: 'Marker Size',
  markerStroke: 'Marker Stroke',
  markerPadding: 'Marker Padding',
  itemSpacing: 'Item Spacing',
  itemPaddingX: 'Item Padding X',
  itemPaddingY: 'Item Padding Y',
  layoutHorizontalSpacing: 'Horizontal Spacing',
  layoutVerticalSpacing: 'Vertical Spacing',
  strokeWidth: 'Stroke Width',
  lineDash: 'Line Dash',
  offset: 'Offset',
  offsets: 'Offsets',
  tooltips: 'Tooltips',
  callout: 'Callout',
  markers: 'Markers',
  shadow: 'Shadow',
  blur: 'Blur',
  xOffset: 'X Offset',
  yOffset: 'Y Offset',
  lineWidth: 'Line Width',
  normal: 'Normal',
  bold: 'Bold',
  italic: 'Italic',
  boldItalic: 'Bold Italic',
  predefined: 'Predefined',
  fillOpacity: 'Fill Opacity',
  strokeOpacity: 'Line Opacity',
  histogramBinCount: 'Bin count',
  columnGroup: 'Column',
  barGroup: 'Bar',
  pieGroup: 'Pie',
  lineGroup: 'Line',
  scatterGroup: 'X Y (Scatter)',
  areaGroup: 'Area',
  histogramGroup: 'Histogram',
  combinationGroup: 'Combination',
  groupedColumnTooltip: 'Grouped',
  stackedColumnTooltip: 'Stacked',
  normalizedColumnTooltip: '100% Stacked',
  groupedBarTooltip: 'Grouped',
  stackedBarTooltip: 'Stacked',
  normalizedBarTooltip: '100% Stacked',
  pieTooltip: 'Pie',
  doughnutTooltip: 'Doughnut',
  lineTooltip: 'Line',
  groupedAreaTooltip: 'Area',
  stackedAreaTooltip: 'Stacked',
  normalizedAreaTooltip: '100% Stacked',
  scatterTooltip: 'Scatter',
  bubbleTooltip: 'Bubble',
  histogramTooltip: 'Histogram',
  columnLineComboTooltip: 'Column & Line',
  areaColumnComboTooltip: 'Area & Column',
  customComboTooltip: 'Custom Combination',
  noDataToChart: 'No data available to be charted.',
  pivotChartRequiresPivotMode: 'Pivot Chart requires Pivot Mode enabled.',
  chartSettingsToolbarTooltip: 'Menu',
  chartLinkToolbarTooltip: 'Linked to Grid',
  chartUnlinkToolbarTooltip: 'Unlinked from Grid',
  chartDownloadToolbarTooltip: 'Download Chart',
  seriesChartType: 'Series Chart Type',
  seriesType: 'Series Type',
  secondaryAxis: 'Secondary Axis',

  // ARIA
  ariaChecked: 'checked',
  ariaColumn: 'Column',
  ariaColumnGroup: 'Column Group',
  ariaColumnList: 'Column List',
  ariaColumnSelectAll: 'Toggle Select All Columns',
  ariaDateFilterInput: 'Date Filter Input',
  ariaDefaultListName: 'List',
  ariaFilterColumnsInput: 'Filter Columns Input',
  ariaFilterFromValue: 'Filter from value',
  ariaFilterInput: 'Filter Input',
  ariaFilterList: 'Filter List',
  ariaFilterToValue: 'Filter to value',
  ariaFilterValue: 'Filter Value',
  ariaFilteringOperator: 'Filtering Operator',
  ariaHidden: 'hidden',
  ariaIndeterminate: 'indeterminate',
  ariaInputEditor: 'Input Editor',
  ariaMenuColumn: 'Press CTRL ENTER to open column menu.',
  ariaRowDeselect: 'Press SPACE to deselect this row',
  ariaRowSelectAll: 'Press Space to toggle all rows selection',
  ariaRowToggleSelection: 'Press Space to toggle row selection',
  ariaRowSelect: 'Press SPACE to select this row',
  ariaSearch: 'Search',
  ariaSortableColumn: 'Press ENTER to sort',
  ariaToggleVisibility: 'Press SPACE to toggle visibility',
  ariaUnchecked: 'unchecked',
  ariaVisible: 'visible',
  ariaSearchFilterValues: 'Search filter values',

  // ARIA Labels for Drop Zones

  ariaRowGroupDropZonePanelLabel: 'Row Groups',
  ariaValuesDropZonePanelLabel: 'Values',
  ariaPivotDropZonePanelLabel: 'Column Labels',
  ariaDropZoneColumnComponentDescription: 'Press DELETE to remove',
  ariaDropZoneColumnValueItemDescription:
    'Press ENTER to change the aggregation type',
  ariaDropZoneColumnGroupItemDescription: 'Press ENTER to sort',
  // used for aggregate drop zone, format: {aggregation}{ariaDropZoneColumnComponentAggFuncSeperator}{column name}
  ariaDropZoneColumnComponentAggFuncSeperator: ' of ',
  ariaDropZoneColumnComponentSortAscending: 'ascending',
  ariaDropZoneColumnComponentSortDescending: 'descending',

  // ARIA Labels for Dialogs
  ariaLabelColumnMenu: 'Column Menu',
  ariaLabelCellEditor: 'Cell Editor',
  ariaLabelDialog: 'Dialog',
  ariaLabelSelectField: 'Select Field',
  ariaLabelTooltip: 'Tooltip',
  ariaLabelContextMenu: 'Context Menu',
  ariaLabelSubMenu: 'SubMenu',
  ariaLabelAggregationFunction: 'Aggregation Function',

  // Number Format (Status Bar, Pagination Panel)
  thousandSeparator: ',',
  decimalSeparator: '.',
};
