export const COMPANY_DYNAMIC_LIST_FIELDS = {
  Action: 'Action',
  'Company code': 'Company code',
  'Company name': 'Company name',
  'Phone number': 'Phone number',
  Country: 'Country',
  'State/ Province': 'State/ Province',
  'Town/ City': 'Town/ City',
  Address: 'Address',
  Fax: 'Fax',
  Email: 'Email',
  Status: 'Status',
};

export const COMPANY_DYNAMIC_DETAIL_FIELDS = {
  'The email has a wrong format, please update it. For example: abc@gmail.com':
    'The email has a wrong format, please update it. For example: abc@gmail.com',
  'Minimum length is 5 characters': 'Minimum length is 5 characters',
  'Maximum length is 15 characters': 'Maximum length is 15 characters',
  'Select an image': 'Select an image',
  Browser: 'Browser',
  Status: 'Status',
  'Company type': 'Company type',
  'Company name': 'Company name',
  'Enter company name': 'Enter company name',
  'Company abbreviation': 'Company abbreviation',
  'Enter company abbreviation': 'Enter company abbreviation',
  'Company code': 'Company code',
  'Enter company code': 'Enter company code',
  'Company IMO': 'Company IMO',
  'Enter company IMO': 'Enter company IMO',
  "Company's level": "Company's level",
  'Allowed subscriptions': 'Allowed subscriptions',
  'Inspections/Services': 'Inspections/Services',
  'Quality assurance': 'Quality assurance',
  'Subscription as': 'Subscription as',
  'Service provider inspection': 'Service provider inspection',
  'Service consumer inspection': 'Service consumer inspection',
  'Main - QA': 'Main - QA',
  'External - QA': 'External - QA',
  'Visible in Global Marketplace': 'Visible in Global Marketplace',
  'Address information': 'Address information',
  Country: 'Country',
  'State/ Province': 'State/ Province',
  'Selected cities': 'Selected cities',
  'Town/ City': 'Town/ City',
  'Enter town/ city': 'Enter town/ city',
  'Enter address': 'Enter address',
  Address: 'Address',
  'Contact information': 'Contact information',
  'Enter first name': 'Enter first name',
  'First name': 'First name',
  'Enter last name': 'Enter last name',
  'Last name': 'Last name',
  'Enter email': 'Enter email',
  'Subscription package': 'Subscription package',
  'Subscription type': 'Subscription type',
  'Enter total number of users': 'Enter total number of users',
  Email: 'Email',
  Fax: 'Fax',
  iNautix: 'iNautix',
  Company: 'Company',
  'Enter phone number': 'Enter phone number',
  'Phone number': 'Phone number',
  'Enter fax': 'Enter fax',
  'Enter sender mail': 'Enter sender mail',
  'Sender mail': 'Sender mail',
  'Total number of jobs': 'Total number of jobs',
  'Total number of users': 'Total number of users',
  Recipient: 'Recipient',
  'Start date': 'Start date',
  'End date': 'End date',
  'Mail management': 'Mail management',
  'Enter recipient': 'Enter recipient',
  'General information': 'General information',
  'Enter total number of jobs': 'Enter total number of jobs',
  'Mail address of sender': 'Mail address of sender',
  'Please enter to add the mail address':
    'Please enter to add the mail address',
  'The mail will be sent by default i-Nautix email address':
    'The mail will be sent by default i-Nautix email address',
};
