export const CREW_GROUPING_FIELDS_LIST = {
  Action: 'Action',
  'Crew grouping code': 'Crew grouping code',
  'Crew grouping name': 'Crew grouping name',
  Officers: 'Officers',
  Rating: 'Rating',
  Description: 'Description',
  Status: 'Status',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Created by company': 'Created by company',
  'Crew Grouping': 'Crew Grouping',
  'Crew grouping information': 'Crew grouping information',
  'Create New': 'Create New',
  Cancel: 'Cancel',
  Delete: 'Delete',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const CREW_GROUPING_FIELDS_DETAILS = {
  Action: 'Action',
  'Crew grouping code': 'Crew grouping code',
  'Crew grouping name': 'Crew grouping name',
  Officers: 'Officers',
  Rating: 'Rating',
  Description: 'Description',
  Status: 'Status',
  Active: 'Active',
  Inactive: 'Inactive',
  'Crew Grouping': 'Crew Grouping',
  Cancel: 'Cancel',
  Save: 'Save',
  'Save & New': 'Save & New',
  'Crew grouping information': 'Crew grouping information',
  checkbox: 'checkbox',
  'Enter crew grouping code': 'Enter crew grouping code',
  'Enter crew grouping name': 'Enter crew grouping name',
  'Enter description': 'Enter description',
  'The crew grouping code is existed': 'The crew grouping code is existed',
  'The crew grouping name is existed': 'The crew grouping name is existed',
};
