export const DEPARTMENT_FIELDS_LIST = {
  Action: 'Action',
  'Department code': 'Department code',
  'Department name': 'Department name',
  Type: 'Type',
  Description: 'Description',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Create New': 'Create New',
  Status: 'Status',
  'Created by company': 'Created by company',
  'Department information': 'Department information',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const DEPARTMENT_FIELDS_DETAILS = {
  'Department code': 'Department code',
  'Department name': 'Department name',
  Type: 'Type',
  Shore: 'Shore',
  Ship: 'Ship',
  Rank: 'Rank',
  Description: 'Description',
  Status: 'Status',
  'Department information': 'Department information',
  Active: 'Active',
  Inactive: 'Inactive',
  'Enter department code': 'Enter department code',
  'Enter department name': 'Enter department name',
  'Enter description': 'Enter description',
  'Please select': 'Please select',
  'Select all': 'Select all',
  Selected: 'Selected',
  Cancel: 'Cancel',
  Save: 'Save',
  'Save & New': 'Save & New',
};
