export const DIVISION_FIELDS_LIST = {
  Action: 'Action',
  'Division code': 'Division code',
  'Division name': 'Division name',
  Description: 'Description',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Created by company': 'Created by company',
  Status: 'Status',
  Division: 'Division',
  'Create New': 'Create New',
  Cancel: 'Cancel',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const DIVISION_FIELDS_DETAILS = {
  'Division code': 'Division code',
  'Division name': 'Division name',
  Description: 'Description',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Created by company': 'Created by company',
  Status: 'Status',
  Active: 'Active',
  Inactive: 'Inactive',
  Division: 'Division',
  Cancel: 'Cancel',
  Save: 'Save',
  'Save & New': 'Save & New',
  'Enter division code': 'Enter division code',
  'Enter division name': 'Enter division name',
  'Enter description': 'Enter description',
  'Update division successfully': 'Update division successfully',
  'Create division successfully': 'Create division successfully',
};
