export const HOME_PAGE_DYNAMIC_LABEL = {
  Homepage: 'Homepage',
  Welcome: 'Welcome',
  Watchlist: 'Watchlist',
  All: 'All',
  'Vessel screening': 'Vessel screening',
  'High potential risks': 'High potential risks',
  'High observed risks': 'High observed risks',
  'Open actionables': 'Open actionables',
  'Overdue actionables': 'Overdue actionables',
  'New/Yet to start jobs': 'New/Yet to start jobs',
  'Open records': 'Open records',
  Overdues: 'Overdues',
  Calendar: 'Calendar',
  'My activity': 'My activity',
  Record: 'Record',
  'updated information': 'updated information',
  'Status changed': 'Status changed',
  'Aging open records': 'Aging open records',
  'Life cycle & Workflow stages': 'Life cycle & Workflow stages',
  '< 15 days': '< 15 days',
  '15 to 30 days': '15 to 30 days',
  '31 to 60 days': '31 to 60 days',
  '> 60 days': '> 60 days',
  Action: 'Action',
  'S.No': 'S.No',
  Remark: 'Remark',
  Remarks: 'Remarks',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'View remark': 'View remark',
  'Edit remark': 'Edit remark',
  'Add remark': 'Add remark',
  Cancel: 'Cancel',
  Save: 'Save',
};
