export const LIST_INSPECTION_TIME_TABLE_DYNAMIC_FIELDS = {
  'On Revoke your submitted task will be reverted to you if no one has claimed yet. Do you want to proceed?':
    'On Revoke your submitted task will be reverted to you if no one has claimed yet. Do you want to proceed?',
  'On Recall your submitted task will be reverted to you if no one has claimed yet. Do you want to proceed?':
    'On Revoke your submitted task will be reverted to you if no one has claimed yet. Do you want to proceed?',
  No: 'No',
  Yes: 'Yes',
  Action: 'Action',
  'Reference number': 'Reference number',
  'Inspection Ref.ID': 'Inspection Ref.ID',
  Entity: 'Entity',
  'Fleet name': 'Fleet name',
  'Vessel name': 'Vessel name',
  'Vessel type': 'Vessel type',
  'Vessel flag': 'Vessel flag',
  Company: 'Company',
  Department: 'Department',
  'Inspection S.No': 'Inspection S.No',
  'Inspection type': 'Inspection type',
  'Lead inspector name': 'Lead inspector name',
  'Planned from date': 'Planned from date',
  'Planned to date': 'Planned to date',
  'S.No': 'S.No',
  Status: 'Status',
  'Created by company': 'Created by company',
  'Revoke/ Recall': 'Revoke/ Recall',
  'Create New': 'Create New',
  Search: 'Search',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const DETAIL_INSPECTION_TIME_TABLE_DYNAMIC_FIELDS = {
  Back: 'Back',
  Entity: 'Entity',
  Auditee: 'Auditee',
  'Area/ Process/ Function': 'Area/ Process/ Function',
  To: 'To',
  From: 'From',
  Date: 'Date',
  'S.No': 'S.No',
  'Enter chief of engineer': 'Enter chief of engineer',
  'Enter master': 'Enter master',
  'Scheduler reference.No.': 'Scheduler reference.No.',
  'Scheduler S.No.': 'Scheduler S.No.',
  Vessel: 'Vessel',
  Company: 'Company',
  'Workflow progress': 'Workflow progress',
  Delete: 'Delete',
  'Choose planning': 'Choose planning',
  Attach: 'Attach',
  'Company name': 'Company name',
  'Lead inspector': 'Lead inspector',
  Inspector: 'Inspector',
  'Inspection type': 'Inspection type',
  'Planned from': 'Planned from',
  'Planned to': 'Planned to',
  Memo: 'Memo',
  'Actual from': 'Actual from',
  'Actual to': 'Actual to',
  Scope: 'Scope',
  'Checklist view': 'Checklist view',
  'Checklist code': 'Checklist code',
  'Checklist name': 'Checklist name',
  'Last updated date': 'Last updated date',
  'Inspection time table': 'Inspection time table',
  Attachments: 'Attachments',
  Action: 'Action',
  'File name': 'File name',
  'File size': 'File size',
  'Uploaded date time': 'Uploaded date time',
  'Uploaded by': 'Uploaded by',
  Cancel: 'Cancel',
  Save: 'Save',
  Submit: 'Submit',
  Edit: 'Edit',
  'Lead auditor': 'Lead auditor',
  'Vessel name': 'Vessel name',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  'Enter scope': 'Enter scope',
};
