export const LIST_INSPECTION_WORKSPACE_DYNAMIC_FIELDS = {
  Action: 'Action',
  'Ref.ID': 'Ref.ID',
  'Plan ID': 'Plan ID',
  'Fleet name': 'Fleet name',
  'Vessel name': 'Vessel name',
  'Vessel type': 'Vessel type',
  Status: 'Status',
  'Global status': 'Global status',
  Flag: 'Flag',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Switch status': 'Switch status',
  Entity: 'Entity',
  Company: 'Company',
  Department: 'Department',
  'Created by company': 'Created by company',
};

export const DETAIL_INSPECTION_WORKSPACE_DYNAMIC_FIELDS = {
  Export: 'Export',
  Back: 'Back',
  Edit: 'Edit',
  Guideline: 'Guideline',
  Master: 'Master',
  Summary: {
    Summary: 'Summary',
    'Enter master': 'Enter master',
    'Enter chief of engineer': 'Enter chief of engineer',
    'Global status': 'Global status',
    'CAR/CAP': 'CAR/CAP',
    Close: 'Close',
    Status: 'Status',
    'Vessel information': 'Vessel information',
    'View details': 'View details',
    'Vessel name': 'Vessel name',
    'Vessel type': 'Vessel type',
    Fleet: 'Fleet',
    'Vessel built on': 'Vessel built on',
    'Vessel current age': 'Vessel current age',
    'Ship manager name': 'Ship manager name',
    Master: 'Master',
    'Audit log': 'Audit log',
    'Chief of engineer': 'Chief of engineer',
    'Inspection report': 'Inspection report',
    'Office information': 'Office information',
    'Company name': 'Company name',
    'Department name': 'Department name',
    'Date of initiating report': 'Date of initiating report',
    'Date of 1st submission': 'Date of 1st submission',
    'Date of report approval': 'Date of report approval',
    'Date of report dispatched': 'Date of report dispatched',
    'Inspection performance': 'Inspection performance',
    'Inspection score': 'Inspection score',
    'Vessel potential risk': 'Vessel potential risk',
    'Office potential risk': 'Office potential risk',
    'Scheduler information': 'Scheduler information',
    'Plan ID': 'Plan ID',
    'Working type': 'Working type',
    'Visit type': 'Visit type',
    'Inspector name': 'Inspector name',
    'Planned from': 'Planned from',
    'Planned to': 'Planned to',
    'Port from': 'Port from',
    'Port to': 'Port to',
    'User memo': 'User memo',
    'Report of finding': 'Report of finding',
    'Total no of findings': 'Total no of findings',
    'Total no of NC/CAR': 'Total no of NC/CAR',
    'CAR issued date': 'CAR issued date',
    'CAP received date': 'CAP received date',
    'Total no of CAP': 'Total no of CAP',
    'Total no of open CAR': 'Total no of open CAR',
    'Total no of closed CAR': 'Total no of closed CAR',
    'Total no of denied CAP': 'Total no of denied CAP',
    'Total no of accepted CAP': 'Total no of accepted CAP',
    'Verification needed CAR': 'Verification needed CAR',
    'Pending verification CAR': 'Pending verification CAR',
    'Inspection history': 'Inspection history',
    Action: 'Action',
    'Inspection Ref.ID': 'Inspection Ref.ID',
    'Inspection type': 'Inspection type',
    'From date': 'From date',
    'To date': 'To date',
    Place: 'Place',
    Type: 'Type',
    'Total no of open findings': 'Total no of open findings',
    'Findings/Corrective action request summary':
      'Findings/Corrective action request summary',
    'Total no of CAR': 'Total no of CAR',
  },
  'Checklist information': {
    'Checklist information': 'Checklist information',
    'App instance ID': 'App instance ID',
    'Add evidence': 'Add evidence',
    'App instance': 'App instance',
    'Inspection type': 'Inspection type',
    'Web instance ID': 'Web instance ID',
    'Publish date': 'Publish date',
    'Report of finding': 'Report of finding',
    'Choose your answer': 'Choose your answer',
    'Enter findings/remarks': 'Enter findings/remarks',
    'Enter memo': 'Enter memo',
    'Main category': 'Main category',
    Evidence: 'Evidence',
    'References and Categories': 'References and Categories',
    Memo: 'Memo',
    'Attach image': 'Attach image',
    'View image': 'View image',
    'Checklist code': 'Checklist code',
    'Findings type': 'Findings type',
    'Is significant': 'Is significant',
    'Second category': 'Second category',
    'Third category': 'Third category',
    'Rectified on board': 'Rectified on board',
    'Checklist name': 'Checklist name',
    'Checklist type': 'Checklist type',
    'Checklist status': 'Checklist status',
    'Revision number': 'Revision number',
    'Revision date': 'Revision date',
    'Publish on': 'Publish on',
    'Submitted on': 'Submitted on',
    'Submitted by': 'Submitted by',
    'Last updated on': 'Last updated on',
    'Last updated by': 'Last updated by',
    'Number of questions': 'Number of questions',
    'Pending questions': 'Pending questions',
    'Completed questions': 'Completed questions',
    'Number of findings': 'Number of findings',
    'Valid from': 'Valid from',
    'Valid to': 'Valid to',
    'Color topic': 'Color topic',
    Question: 'Question',
    'Findings/Remarks': 'Findings/Remarks',
    Attachment: 'Attachment',
    'View evidence': 'View evidence',
    'Update by': 'Update by',
    'Category mapping': 'Category mapping',
  },
  'Finding summary': {
    'Finding summary': 'Finding summary',
    Action: 'Action',
    'Rof.ID': 'Rof.ID',
    'Ir.ID': 'Ir.ID',
    'App instance ID': 'App instance ID',
    'Web instance ID': 'Web instance ID',
    'Template code': 'Template code',
    'Onboard finding summary': 'Onboard finding summary',
    'Submit to final': 'Submit to final',
    'Question name': 'Question name',
    Reference: 'Reference',
    'Inspection type': 'Inspection type',
    'Finding type': 'Finding type',
    'Is significant': 'Is significant',
    'Main category': 'Main category',
    'Second category': 'Second category',
    'Third category': 'Third category',
    Finding: 'Finding',
    'Rectification/ verified': 'Rectification/ verified',
    'Question ID': 'Question ID',
    'Finding detail': 'Finding detail',
    Question: 'Question',
    'Rectified on board': 'Rectified on board',
  },
  Remarks: {
    Remarks: 'Remarks',
    Action: 'Action',
    'S.No': 'S.No',
    Title: 'Title',
    Security: 'Security',
    'Created by': 'Created by',
    Add: 'Add',
    Attachments: 'Attachments',
    Attach: 'Attach',
    'Enter title': 'Enter title',
    'Delete?': 'Delete?',
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
      'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
    'Enter remarks': 'Enter remarks',
    'File name': 'File name',
    'File size': 'File size',
    'Uploaded date time': 'Uploaded date time',
    'Uploaded by': 'Uploaded by',
    'Total size': 'Total size',
    'Zip file': 'Zip file',
    'Zip files': 'Zip files',
  },
  Analytical: {
    Analytical: 'Analytical',
    'Inspection performance calculation': 'Inspection performance calculation',
    'Inspection performance range': 'Inspection performance range',
    'Total questions': 'Total questions',
    'Question marked with value': 'Question marked with value',
    'Total questions verified': 'Total questions verified',
    Finding: 'Finding',
    'Inspection score': 'Inspection score',
    'Inspection performance': 'Inspection performance',
    'Potential risks range': 'Potential risks range',
    Q: 'Q',
    'Potential risk': 'Potential risk',
    'Weighted score': 'Weighted score',
    'Total findings': 'Total findings',
    IMO: 'IMO',
    'Vessel name': 'Vessel name',
    'Detailed analytic report': 'Detailed analytic report',
    'Risk rating': 'Risk rating',
    'Risk is represented as a value': 'Risk is represented as a value',
    Action: 'Action',
    'S.No': 'S.No',
    'Report of finding': 'Report of finding',
    'Percent off': 'Percent off',
    'Red (0-50)': 'Red (0-50)',
    'Orange (51-70)': 'Orange (51-70)',
    'Yellow (71-85)': 'Yellow (71-85)',
    'Green (> 85)': 'Green (> 85)',
    'Negligible (0)': 'Negligible (0)',
    'Low (1-19)': 'Low (1-19)',
    'Medium (20-49)': 'Medium (20-49)',
    'High (>=50)': 'High (>=50)',
    Reason: 'Reason',
    'Points off': 'Points off',
    'Vessel potential risk': 'Vessel potential risk',
    Apply: 'Apply',
    'Score adjustment': 'Score adjustment',
    'Repeated findings': 'Repeated findings',
    'Question code': 'Question code',
    'Ref.ID': 'Ref.ID',
    'Date of inspection': 'Date of inspection',
    Item: 'Item',
    'Original value': 'Original value',
    'Suggested value': 'Suggested value',
    'Repeated company findings': 'Repeated company findings',
    Export: 'Export',
    'Analytic report': 'Analytic report',
    Master: 'Master',
    'Chief engineer': 'Chief engineer',
    'Vessel type': 'Vessel type',
    Location: 'Location',
    'Second category': 'Second category',
    'Age (YY.MM)': 'Age (YY.MM)',
    'Ship yard': 'Ship yard',
    'Port of inspection': 'Port of inspection',
    'Shipyard country': 'Shipyard country',
    'Inspector name': 'Inspector name',
    'Size (GRT)': 'Size (GRT)',
    'Category overview': 'Category overview',
    'Location overview': 'Location overview',
    CATEGORY: 'CATEGORY',
    'POTENTIAL RISKS FINDING COUNT': 'POTENTIAL RISKS FINDING COUNT',
    UNASSIGNED: 'UNASSIGNED',
    NEGLIGIBLE: 'NEGLIGIBLE',
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    TOTAL: 'TOTAL',
    'Grand total': 'Grand total',
    'Total checklist items': 'Total checklist items',
    'Verified items': 'Verified items',
    'Total number of findings': 'Total number of findings',
    Reject: 'Reject',
    Accept: 'Accept',
    'Main category': 'Main category',
    'Location wise': 'Location wise',
    'Total weighted score': 'Total weighted score',
    '(-ve signs for the weighted scores have been omitted for graphical representation on the below graphs)':
      '(-ve signs for the weighted scores have been omitted for graphical representation on the below graphs)',
    CODE: 'CODE',
    ITEM: 'ITEM',
    FINDING: 'FINDING',
    'RECTIEFIED ON BOARD': 'RECTIEFIED ON BOARD',
    'Detailed Analytic Report': 'Detailed Analytic Report',
    'DETAILED SUB CATEGORY WISE': 'DETAILED SUB CATEGORY WISE',
    'WEIGHTED SCORE': 'WEIGHTED SCORE',
    'Incorrect checklist template': 'Incorrect checklist template',
    'Please ensure that you are using correct Template Checklist while generating Analytical Report':
      'Please ensure that you are using correct Template Checklist while generating Analytical Report',
    '“The content of this document may not be used for purposes other than that for which it has been supplied and may not be reproduced, either wholly or in part, in any way whatsoever, nor may it be used by, or its content divulged to, any other person or third party without prior written consent. This report is issued without any prejudice to any or all parties concerned on the condition that all parties concerned, waive rights to hold the auditing company or author liable in respect of any consequences arising from the use of the information contained (or not mentioned) in this report.”':
      '“The content of this document may not be used for purposes other than that for which it has been supplied and may not be reproduced, either wholly or in part, in any way whatsoever, nor may it be used by, or its content divulged to, any other person or third party without prior written consent. This report is issued without any prejudice to any or all parties concerned on the condition that all parties concerned, waive rights to hold the auditing company or author liable in respect of any consequences arising from the use of the information contained (or not mentioned) in this report.”',
    Save: 'Save',
    Close: 'Close',
    Unassigned: 'Unassigned',
    Low: 'Low',
    Medium: 'Medium',
    High: 'High',
    Negligible: 'Negligible',
    'Negligible risk': 'Negligible risk',
    'Low risk': 'Low risk',
    'Medium risk': 'Medium risk',
    'High risk': 'High risk',
  },
};
