export const LIST_INSPECTION_FOLLOW_UP_DYNAMIC_FIELDS = {
  Action: 'Action',
  'Ref.ID': 'Ref.ID',
  'ROF Ref.ID': 'ROF Ref.ID',
  Entity: 'Entity',
  'Vessel name': 'Vessel name',
  'Vessel type': 'Vessel type',
  Company: 'Company',
  Department: 'Department',
  'Lead inspector name': 'Lead inspector name',
  Status: 'Status',
  'Global status': 'Global status',
  'Total number of CAR': 'Total number of CAR',
  'Total number of closed CAR': 'Total number of closed CAR',
  'Total number of CAP': 'Total number of CAP',
  'Total number of accepted CAP': 'Total number of accepted CAP',
  'Total number of denied CAP': 'Total number of denied CAP',
  'Created by company': 'Created by company',
};

export const DETAIL_INSPECTION_FOLLOW_UP_DYNAMIC_FIELDS = {
  'Ref.ID': 'Ref.ID',
  Status: 'Status',
  'Global status': 'Global status',
  'General information': 'General information',
  'Company name': 'Company name',
  'Vessel name': 'Vessel name',
  'Enter comment': 'Enter comment',
  'CAP PIC': 'CAP PIC',
  'CAR status': 'CAR status',
  CAP: 'CAP',
  Department: 'Department',
  'Inspection number': 'Inspection number',
  'Inspection type': 'Inspection type',
  'Lead inspector name': 'Lead inspector name',
  'Inspector name': 'Inspector name',
  'Preventive action': 'Preventive action',
  'CAP status': 'CAP status',
  'Actual inspection from port': 'Actual inspection from port',
  'Actual inspection to port': 'Actual inspection to port',
  'Planned from date': 'Planned from date',
  'Planned to date': 'Planned to date',
  'CAR / CAP summary': 'CAR / CAP summary',
  'Total no of CAR': 'Total no of CAR',
  'Total no of open CAR': 'Total no of open CAR',
  'Total no of closed CAR': 'Total no of closed CAR',
  'CAR (Corrective action request)': 'CAR (Corrective action request)',
  Action: 'Action',
  'CAR S.No': 'CAR S.No',
  'CAR comment': 'CAR comment',
  'Vessel manager': 'Vessel manager',
  'CAP (Corrective action plan)': 'CAP (Corrective action plan)',
  'Inspection management team comment': 'Inspection management team comment',
  'Add comment': 'Add comment',
  'Office comment': 'Office comment',
  'S.No': 'S.No',
  Comment: 'Comment',
  'Commented by': 'Commented by',
  'Job title': 'Job title',
  'Commented date': 'Commented date',
  'Root cause': 'Root cause',
};
