export const INSPECTION_DASHBOARD_DYNAMIC_FIELDS = {
  'Inspection dashboard': 'Inspection dashboard',
  'Avg. findings per inspection plan': 'Avg. findings per inspection plan',
  'Rate of overdue reports': 'Rate of overdue reports',
  'Average workload of auditor by month':
    'Average workload of auditor by month',
  'View more': 'View more',
  'Total findings (last 30 days)': 'Total findings (last 30 days)',
  'Inspection checklist status': 'Inspection checklist status',
  'Total number of yet to start inspection checklist':
    'Total number of yet to start inspection checklist',
  'Total number of in progress inspection checklist':
    'Total number of in progress inspection checklist',
  'Total number of completed inspection checklist':
    'Total number of completed inspection checklist',
  'Report of findings status': 'Report of findings status',
  'Total number of draft report of findings':
    'Total number of draft report of findings',
  'Total number of submitted report of findings':
    'Total number of submitted report of findings',
  'Total number of reviewed report of findings':
    'Total number of reviewed report of findings',
  'Total number of close out report of findings':
    'Total number of close out report of findings',
  'Inspection report status': 'Inspection report status',
  'Total number of submitted inspection report':
    'Total number of submitted inspection report',
  'Total number of draft inspection report':
    'Total number of draft inspection report',
  'Total number of submiteed inspection report':
    'Total number of submiteed inspection report',
  'Total number of reviewed inspection report':
    'Total number of reviewed inspection report',
  'Total number of approved inspection report':
    'Total number of approved inspection report',
  'Total number of close out inspection report':
    'Total number of close out inspection report',
  'Trends of audit & inspection activities':
    'Trends of audit & inspection activities',
  'Total findings by main category': 'Total findings by main category',
  'Average findings per inspection plan':
    'Average findings per inspection plan',
  'Average workload of auditor': 'Average workload of auditor',
  'Open tasks': 'Open tasks',
  'Inspection checklist templates': 'Inspection checklist templates',
  Submitted: 'Submitted',
  Reviewed: 'Reviewed',
  Approved: 'Approved',
  Planning: 'Planning',
  Accepted: 'Accepted',
  'Number of upcoming inspection plans': 'Number of upcoming inspection plans',
  'Number of inspection audit reports not closed out':
    'Number of inspection audit reports not closed out',
  'Report of findings': 'Report of findings',
  'Inspection reports': 'Inspection reports',
  'Number of upcoming reports': 'Number of upcoming reports',
  'Inspection plans': 'Inspection plans',
  'Upcoming inspection plans': 'Upcoming inspection plans',
  'Current Date': 'Current Date',
  'CAR/CAP needs reviewing': 'CAR/CAP needs reviewing',
  'Lead auditor': 'Lead auditor',
  'Planned audit from date': 'Planned audit from date',
  'Report of findings Ref.ID': 'Report of findings Ref.ID',
  CAP: 'CAP',
  'Inspection time table S.No': 'Inspection time table S.No',
  'Reference number': 'Reference number',
  'Plan Ref.ID': 'Plan Ref.ID',
  'S.No': 'S.No',
  'Total open non-conformity': 'Total open non-conformity',
  'Total open non-conformity findings': 'Total open non-conformity findings',
  'Lead inspector name': 'Lead inspector name',
  'Lead inspector': 'Lead inspector',
  'Total open observation findings': 'Total open observation findings',
  'Estimated closure date': 'Estimated closure date',
  'Number of findings': 'Number of findings',
  'Actual closure date': 'Actual closure date',
  Entity: 'Entity',
  PIC: 'PIC',
  'Inspection report Ref.ID': 'Inspection report Ref.ID',
  'Findings Ref.No': 'Findings Ref.No',
  'Inspection type': 'Inspection type',
  Findings: 'Findings',
  'Is significant': 'Is significant',
  Action: 'Action',
  'Vessel name': 'Vessel name',
  'Audit Ref.Id': 'Audit Ref.Id',
  'Actual Inspection From Date': 'Actual Inspection From Date',
  'Inspection report S.No': 'Inspection report S.No',
  'Report S.No': 'Report S.No',
  Status: 'Status',
  'Audit plan ref. ID': 'Audit plan ref. ID',
  'Planned inspection date from': 'Planned inspection date from',
  'Planned Inspection Date From': 'Planned Inspection Date From',
  'Inspection plans need reviewing': 'Inspection plans need reviewing',
  'Number of inspection reports not closed out':
    'Number of inspection reports not closed out',
  'Planned Inspection Date To': 'Planned Inspection Date To',
  'Company name': 'Company name',
  'Trends of outstanding CAR/CAP issue': 'Trends of outstanding CAR/CAP issue',
  'Outstanding CAR/CAP issue': 'Outstanding CAR/CAP issue',
  'Number of open CAR': 'Number of open CAR',
  'Number of hold CAP': 'Number of hold CAP',
  'Number of pending CAP': 'Number of pending CAP',
  'Number of denied CAP': 'Number of denied CAP',
  'Trends of outstanding issues': 'Trends of outstanding issues',
  'Number of non-conformity /observations':
    'Number of non-conformity /observations',
  'Number of inspection time tables not closed out':
    'Number of inspection time tables not closed out',
  'Number of report of findings not closed out':
    'Number of report of findings not closed out',
  'Planned inspection date to': 'Planned inspection date to',
  'Outstanding issue': 'Outstanding issue',
  'Number of open non-conformity (last 30 days)':
    'Number of open non-conformity (last 30 days)',
  'Inspection plan ID': 'Inspection plan ID',
  'Planned inspection date': 'Planned inspection date',
  'Open non-conformity': 'Open non-conformity',
  'Upcoming inspection plan details': 'Upcoming inspection plan details',
  'Open non-conformity details': 'Open non-conformity details',
  'Number of open observations (last 30 days)':
    'Number of open observations (last 30 days)',
  'Report of findings not closed out': 'Report of findings not closed out',
  'Inspection time tables not closed out':
    'Inspection time tables not closed out',
  'Inspection reports not closed out': 'Inspection reports not closed out',
  'Total upcoming audit plans': 'Total upcoming audit plans',
  'Upcoming audit plans': 'Upcoming audit plans',
  'Upcoming audit plans details': 'Upcoming audit plans details',
  'Total open observations': 'Total open observations',
  'Open observations': 'Open observations',
  'Open observations details': 'Open observations details',
  'Total non-conformity findings': 'Total non-conformity findings',
  'Total upcoming reports': 'Total upcoming reports',
  'Upcoming reports details': 'Upcoming reports details',
  'Upcoming reports': 'Upcoming reports',
  'Average auditor workload (last 30 days)':
    'Average auditor workload (last 30 days)',
  'Number of upcoming audit plans': 'Number of upcoming audit plans',
  'Yet to start': 'Yet to start',
  Inprogress: 'Inprogress',
  Completed: 'Completed',
  'Total findings': 'Total findings',
  'By main category': 'By main category',
  'By location': 'By location',
  Company: 'Company',
  'Ref.ID': 'Ref.ID',
  'Template code': 'Template code',
  'Template name': 'Template name',
  'Revision date': 'Revision date',
  'View More': 'View More',
  Inspector: 'Inspector',
  'Period of time (Days)': 'Period of time (Days)',
  'Inspection time table Ref.ID': 'Inspection time table Ref.ID',
  'Report of findings S.No': 'Report of findings S.No',
  'Actual inspection from date': 'Actual inspection from date',
  'Total number of planned inspection': 'Total number of planned inspection',
  'In-progress plan': 'In-progress plan',
  'Completed plan (last 30 days)': 'Completed plan (last 30 days)',
  'Rejected/ Reassigned': 'Rejected/ Reassigned',
  'Number of upcoming audit plan': 'Number of upcoming audit plan',
  CAR: 'CAR',
};
