export const INSPECTION_REPORT_FIELDS_LIST = {
  Action: 'Action',
  'Ref.ID': 'Ref.ID',
  'Inspection Ref.ID': 'Inspection Ref.ID',
  Entity: 'Entity',
  'Fleet name': 'Fleet name',
  'Vessel name': 'Vessel name',
  'Vessel type': 'Vessel type',
  Flag: 'Flag',
  Company: 'Company',
  Department: 'Department',
  'Lead inspector': 'Lead inspector',
  'Total.No.Findings': 'Total.No.Findings',
  'Total.No.OBS': 'Total.No.OBS',
  'Total.No.NC': 'Total.No.NC',
  'Inspection from date': 'Inspection from date',
  'Inspection to date': 'Inspection to date',
  'Inspection S.No': 'Inspection S.No',
  'S.No': 'S.No',
  Status: 'Status',
  'Global status': 'Global status',
  'Total.No open NC': 'Total.No open NC',
  'Total.No closed NC': 'Total.No closed NC',
  'Total.No open OBS': 'Total.No open OBS',
  'Total.No closed OBS': 'Total.No closed OBS',
  'Created by company': 'Created by company',
};

export const INSPECTION_REPORT_FIELDS_DETAILS = {
  'Inspection report': 'Inspection report',
  'Edit observation': 'Edit observation',
  'Non conformity': 'Non conformity',
  'Enter comment': 'Enter comment',
  'Description/Comments': 'Description/Comments',
  'Export PDF': 'Export PDF',
  'Print option': 'Print option',
  'Please select': 'Please select',
  'Enter name': 'Enter name',
  'Commented by': 'Commented by',
  'S.No': 'S.No',
  Add: 'Add',
  'Updated user': 'Updated user',
  'Job title': 'Job title',
  'Updated date': 'Updated date',
  'Enter close number': 'Enter close number',
  'Number of open findings': 'Number of open findings',
  'Enter total number': 'Enter total number',
  'Total number of findings': 'Total number of findings',
  Findings: 'Findings',
  'Inspection history and status': 'Inspection history and status',
  'Number of close findings': 'Number of close findings',
  'Enter open number': 'Enter open number',
  'Change description': 'Change description',
  'File name': 'File name',
  Comment: 'Comment',
  'Review name': 'Review name',
  'Commented date': 'Commented date',
  'Reviewer comment': 'Reviewer comment',
  Finding: 'Finding',
  'Enter score': 'Enter score',
  'Add cover image': 'Add cover image',
  'Enter remark': 'Enter remark',
  Confirmation: 'Confirmation',
  'Select date': 'Select date',
  Open: 'Open',
  Total: 'Total',
  'i) List of items': 'i) List of items',
  'Internal audit': 'Internal audit',
  'Auto-generated records': 'Auto-generated records',
  Topic: 'Topic',
  Score: 'Score',
  Description: 'Description',
  'Scheduler and report of finding status':
    'Scheduler and report of finding status',
  'Company name': 'Company name',
  'Department name': 'Department name',
  'Cover image': 'Cover image',
  'Actual inspection to date': 'Actual inspection to date',
  'Actual inspection from date': 'Actual inspection from date',
  'Actual inspection from port': 'Actual inspection from port',
  'Scheduler and report of findings status':
    'Scheduler and report of findings status',
  'Actual inspection to port': 'Actual inspection to port',
  'Inspector name': 'Inspector name',
  'Enter description': 'Enter description',
  'General information': 'General information',
  'Office comment': 'Office comment',
  'Add description': 'Add description',
  'Inspection number': 'Inspection number',
  'Inspection date': 'Inspection date',
  'Inspection type': 'Inspection type',
  'Nature of findings': 'Nature of findings',
  'NC verification': 'NC verification',
  'NC status': 'NC status',
  'Vessel name': 'Vessel name',
  'Visit type': 'Visit type',
  'Lead inspector name': 'Lead inspector name',
  'Ref.ID': 'Ref.ID',
  Status: 'Status',
  'Global status': 'Global status',
  Action: 'Action',
  'Scheduler reference': 'Scheduler reference',
  'Scheduler status': 'Scheduler status',
  'Report of findings reference': 'Report of findings reference',
  'Report of findings status': 'Report of findings status',
  Close: 'Close',
  'Finding/Corrective action request summary':
    'Finding/Corrective action request summary',
  'Total no of findings': 'Total no of findings',
  'Total no of CAR': 'Total no of CAR',
  'Total no of open CAR': 'Total no of open CAR',
  'Total no of closed CAR': 'Total no of closed CAR',
  'Total no of CAP': 'Total no of CAP',
  'Total no of accepted CAP': 'Total no of accepted CAP',
  'Total no of denied CAP': 'Total no of denied CAP',
  'List of items': 'List of items',
  From: 'From',
  To: 'To',
  'Manually created records': 'Manually created records',
  Comments: 'Comments',
  'Is significant': 'Is significant',
  PIC: 'PIC',
  'Workflow status': 'Workflow status',
  'CAR/CAP details': 'CAR/CAP details',
  CAR: 'CAR',
  'CAR status': 'CAR status',
  CAP: 'CAP',
  'CAP status': 'CAP status',
  'Verification status': 'Verification status',
  'Verification date': 'Verification date',
  Observation: 'Observation',
  'Edit non conformity': 'Edit non conformity',
  'Rectified on board': 'Rectified on board',
  Department: 'Department',
  'Main category': 'Main category',
  Reference: 'Reference',

  'PIC remark': 'PIC remark',

  'Findings remark': 'Findings remark',
  'Finding status': 'Finding status',
  Remark: 'Remark',
  'Planned completion date': 'Planned completion date',
  'Actual completion date': 'Actual completion date',
  Attachments: 'Attachments',
  Attach: 'Attach',
  'Immediate action': 'Immediate action',
  'Preventive action': 'Preventive action',
  'Corrective action': 'Corrective action',
  'Inspection comments': 'Inspection comments',
  'Executive summary': 'Executive summary',
  'Status of last audit findings': 'Status of last audit findings',
  'Hull and deck': 'Hull and deck',
  Navigation: 'Navigation',
  'Machinery and technical': 'Machinery and technical',
  'Cargo and ballast': 'Cargo and ballast',
  'Crew management': 'Crew management',
  'Pollution prevention': 'Pollution prevention',
  'Safety culture': 'Safety culture',
  Others: 'Others',
  'Enter executive summary': 'Enter executive summary',
  'Enter status of last audit findings': 'Enter status of last audit findings',
  'Enter hull and deck': 'Enter hull and deck',
  'Enter navigation': 'Enter navigation',
  'Enter machinery and technical': 'Enter machinery and technical',
  'Enter cargo and ballast': 'Enter cargo and ballast',
  'Enter crew management': 'Enter crew management',
  'Enter pollution prevention': 'Enter pollution prevention',
  'Enter Safety Culture': 'Enter Safety Culture',
  'Enter others': 'Enter others',
  'User history section': 'User history section',
  'Additional reviewer section': 'Additional reviewer section',
  'Workflow remarks': 'Workflow remarks',
  'Enter workflow remarks': 'Enter workflow remarks',
  'Office comments': 'Office comments',
  'Inspection history': 'Inspection history',
  Cancel: 'Cancel',
  Save: 'Save',
  Submit: 'Submit',
  'Add comment': 'Add comment',
};
