export const INSPECTION_MAPPING_LIST_DYNAMIC_LABELS = {
  Action: 'Action',
  Scope: 'Scope',
  'Inspection type': 'Inspection type',
  'Inspection period (in days)': 'Inspection period (in days)',
  'Mark primary': 'Mark primary',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  Status: 'Status',
  'Created by company': 'Created by company',
  'Confirmation?': 'Confirmation?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  Cancel: 'Cancel',
  Delete: 'Delete',
  'Create New': 'Create New',
};

export const INSPECTION_MAPPING_DETAIL_DYNAMIC_LABELS = {
  'Inspection mapping information': 'Inspection mapping information',
  Scope: 'Scope',
  'Inspection type': 'Inspection type',
  'Inspection period (in days)': 'Inspection period (in days)',
  'Nature of findings': 'Nature of findings',
  'Mark primary findings': 'Mark primary findings',
  Status: 'Status',
  Selected: 'Selected',
  'Ship (no/yes)': 'Ship (no/yes)',
  'Shore (no/yes)': 'Shore (no/yes)',
  'Show VIQ': 'Show VIQ',
  'Inspection checklist template': 'Inspection checklist template',
  'User history section': 'User history section',
  Back: 'Back',
  Edit: 'Edit',
  Delete: 'Delete',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  Confirm: 'Confirm',
  Cancel: 'Cancel',
  'Confirmation?': 'Confirmation?',
  'Are you sure you want to proceed with this action?':
    'Are you sure you want to proceed with this action?',
  'Enter inspection period': 'Enter inspection period',
  'Checklist code': 'Checklist code',
  'Checklist name': 'Checklist name',
  Entity: 'Entity',
  'Revision number': 'Revision number',
  'Revision date': 'Revision date',
  'App type': 'App type',
  'Checklist type': 'Checklist type',
  'Valid form': 'Valid form',
  'Valid to': 'Valid to',
  'Nature of finding code': 'Nature of finding code',
  'Nature of finding name': 'Nature of finding name',
  checkbox: 'checkbox',
  Save: 'Save',
  'Save & New': 'Save & New',
  Action: 'Action',
  'S.No': 'S.No',
  'User name': 'User name',
  'Job title': 'Job title',
  'Update date': 'Update date',
  'Add more': 'Add more',
};
