export const LOCATION_FIELDS_LIST = {
  Action: 'Action',
  'Location code': 'Location code',
  'Location name': 'Location name',
  LocAcronym: 'LocAcronym',
  Description: 'Description',
  Status: 'Status',
  Location: 'Location',
  'Location information': 'Location information',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Created by company': 'Created by company',
  'Create New': 'Create New',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const LOCATION_FIELDS_DETAILS = {
  'Location code': 'Location code',
  'Location name': 'Location name',
  LocAcronym: 'LocAcronym',
  Description: 'Description',
  Status: 'Status',
  Active: 'Active',
  Inactive: 'Inactive',
  'Location information': 'Location information',
  'Enter location code': 'Enter location code',
  'Enter location name': 'Enter location name',
  'Enter description': 'Enter description',
  'Enter locAcronym': 'Enter locAcronym',
  'Inspection Type information': 'Inspection Type information',
};
