export const MAIL_TEMPLATE_DYNAMIC_LIST_FIELDS = {
  Action: 'Action',
  'Mail template code': 'Mail template code',
  'Mail template name': 'Mail template name',
  'Mail type': 'Mail type',
  Status: 'Status',
  To: 'To',
  Subject: 'Subject',
  'Created by company': 'Created by company',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  Cancel: 'Cancel',
  Delete: 'Delete',
  'Create New': 'Create New',
};

export const MAIL_TEMPLATE_DYNAMIC_DETAIL_FIELDS = {
  Edit: 'Edit',
  Back: 'Back',
  Delete: 'Delete',
  Select: 'Select',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  Cancel: 'Cancel',
  'General information': 'General information',
  Entity: 'Entity',
  'Mail template code': 'Mail template code',
  'Mail template name': 'Mail template name',
  Module: 'Module',
  'Working type': 'Working type',
  'Mail type': 'Mail type',
  'Vessel type': 'Vessel type',
  Status: 'Status',
  'Mail template description': 'Mail template description',
  'Mail details': 'Mail details',
  To: 'To',
  'Please enter to add the mail address':
    'Please enter to add the mail address',
  Cc: 'Cc',
  'Please enter cc add the mail address':
    'Please enter cc add the mail address',
  Bcc: 'Bcc',
  'Please enter bcc add the mail address':
    'Please enter bcc add the mail address',
  Subject: 'Subject',
  Body: 'Body',
  'Attachment kit': 'Attachment kit',
  'Enter mail template code': 'Enter mail template code',
  'Enter mail template name': 'Enter mail template name',
  'Enter mail template description': 'Enter mail template description',
  Save: 'Save',
  'Please select': 'Please select',
  'Select all': 'Select all',
  'Please type @ and select field names to populate data when sending mail':
    'Please type @ and select field names to populate data when sending mail',
  'Confirmation?': 'Confirmation?',
  'Are you sure you want to proceed with this action?':
    'Are you sure you want to proceed with this action?',
  'Enter to': 'Enter to',
  'Enter cc': 'Enter cc',
  'Enter bcc': 'Enter bcc',
  'Subject must be smaller than 500': 'Subject must be smaller than 500',
  'The files are exceeding the maximum attachment kit size of 8.5MB, please reduce the files':
    'The files are exceeding the maximum attachment kit size of 8.5MB, please reduce the files',
  Checkbox: 'Checkbox',
  Name: 'Name',
  'Mail address': 'Mail address',
  'Job title': 'Job title',
  Search: 'Search',
  Selected: 'Selected',
  Confirm: 'Confirm',
  'The mail template code is existed': 'The mail template code is existed',
  'Kit name': 'Kit name',
  'Kit description': 'Kit description',
};
