export const MAP_VIEW_DYNAMIC_FIELDS = {
  'Map view': 'Map view',
  'Inspector view': 'Inspector view',
  'Inspection view': 'Inspection view',
  'Base location': 'Base location',
  'Include service area': 'Include service area',
  Company: 'Company',
  'Search availability': 'Search availability',
  'Date range': 'Date range',
  'By country': 'By country',
  'By port': 'By port',
  'Inspector name': 'Inspector name',
  Selected: 'Selected',
  'Select all': 'Select all',
  'Clear all': 'Clear all',
  'Country name': 'Country name',
  Search: 'Search',
  Entity: 'Entity',
  'Port code': 'Port code',
  'Search unassigned inspection plan': 'Search unassigned inspection plan',
  'Inspection no': 'Inspection no',
  'Vessel name': 'Vessel name',
  'Fleet name': 'Fleet name',
  'Vessel type': 'Vessel type',
  'Visit type': 'Visit type',
  'Inspection type': 'Inspection type',
  'Working type': 'Working type',
  'From port': 'From port',
  'To port': 'To port',
  'Planned from date': 'Planned from date',
  'Planned to date': 'Planned to date',
  'Name of inspector': 'Name of inspector',
  'Name of lead inspector': 'Name of lead inspector',
  From: 'From',
  To: 'To',
  'Please select': 'Please select',
  Results: 'Results',
  'Company name': 'Company name',
  Department: 'Department',
  'First name': 'First name',
  'Last name': 'Last name',
  'Job title': 'Job title',
  Nationality: 'Nationality',
  Email: 'Email',
  'Phone number': 'Phone number',
  Gender: 'Gender',
  'Date of birth': 'Date of birth',
};
