export const NOTIFICATION_DYNAMIC_LABELS = {
  Notification: 'Notification',
  'Marked all notification as read': 'Marked all notifications as read',
  'Marked notification as read': 'Marked notification as read',
  'Mark all as read': 'Mark all as read',
  'Mark as read': 'Mark as read',
  'View all notifications': 'View all notifications',
  'Delete notification successfully': 'Delete notification successfully',
  All: 'All',
  Unread: 'Unread',
  Delete: 'Delete',
  Record: 'Record',
  'updated information': 'updated information',
  'Status changed': 'Status changed',

  Search: 'Search',
  'Dear customer': 'Dear customer',
  'There is an update information of record in':
    'There is an update information of record in',
  'in i-Nautix system': 'in i-Nautix system',
  'The status changed from': 'The status changed from',
  to: 'to',
  'Click to view more detail': 'Click to view more detail',
  'Thank you for choosing our system': 'Thank you for choosing our system',
};
