export const LIST_PLANNING_DYNAMIC_FIELDS = {
  'Inspection month': 'Inspection month',
  Status: 'Status',
  Entity: 'Entity',
  'Show unassigned inspector plans': 'Show unassigned inspector plans',
  Search: 'Search',
  'Clear all': 'Clear all',
  'VESSEL NAME': 'VESSEL NAME',
  OFFICE: 'OFFICE',
  'INSPECTOR NAME': 'INSPECTOR NAME',
  'Graphical planning': 'Graphical planning',
  Planning: 'Planning',
  Completed: 'Completed',
  Unplanned: 'Unplanned',
  'Create New': 'Create New',
  Action: 'Action',
  'Ref.ID': 'Ref.ID',
  'Fleet name': 'Fleet name',
  'Vessel name': 'Vessel name',
  'Vessel type': 'Vessel type',
  Flag: 'Flag',
  Company: 'Company',
  Department: 'Department',
  'Working type': 'Working type',
  'Inspection type': 'Inspection type',
  'Visit type': 'Visit type',
  'Date of last inspection': 'Date of last inspection',
  'Due date': 'Due date',
  'Inspection planned from date': 'Inspection planned from date',
  'Inspection planned to date': 'Inspection planned to date',
  'Lead inspector name': 'Lead inspector name',
  'Name of inspector': 'Name of inspector',
  'From port': 'From port',
  'To port': 'To port',
  ETA: 'ETA',
  ETD: 'ETD',
  'Inspection no': 'Inspection no',
  'Schedule status': 'Schedule status',
  'Global status': 'Global status',
  'Created by company': 'Created by company',
};
export const DETAIL_PLANNING_DYNAMIC_FIELDS = {
  Back: 'Back',
  Edit: 'Edit',
  'Start date': 'Start date',
  'Inspector name': 'Inspector name',
  Status: 'Status',
  'Office comment': 'Office comment',
  'End date': 'End date',
  Attach: 'Attach',
  Physical: 'Physical',
  'From port': 'From port',
  'To port': 'To port',
  Remote: 'Remote',
  'Lead inspector name': 'Lead inspector name',
  'S.No': 'S.No',
  'Vessel code': 'Vessel code',
  'Time off type': 'Time off type',
  Delete: 'Delete',
  Close: 'Close',
  'Enter description': 'Enter description',
  'Planned to port': 'Planned to port',
  'Planned from port': 'Planned from port',
  'Enter time off type': 'Enter time off type',
  'Enter memo': 'Enter memo',
  'Company name': 'Company name',
  Submit: 'Submit',
  Fleet: 'Fleet',
  'Inspection time table': 'Inspection time table',
  'Workflow progress': 'Workflow progress',
  Department: 'Department',
  'User history section': 'User history section',
  'General information': 'General information',
  Entity: 'Entity',
  'Vessel name': 'Vessel name',
  'Vessel type': 'Vessel type',
  'Date of last inspection': 'Date of last inspection',
  'Due date': 'Due date',
  'Visit type': 'Visit type',
  'Inspection type': 'Inspection type',
  'Working type': 'Working type',
  'Inspectors schedule': 'Inspectors schedule',
  Port: 'Port',
  'Name of inspector': 'Name of inspector',
  ETA: 'ETA',
  ETD: 'ETD',
  'Planned from date': 'Planned from date',
  'Planned to date': 'Planned to date',
  'Name of lead inspector': 'Name of lead inspector',
  'Please assign inspectors to accept the schedule':
    'Please assign inspectors to accept the schedule',
  'Focus request': 'Focus request',
  Memo: 'Memo',
  Attachments: 'Attachments',
  Action: 'Action',
  'File name': 'File name',
  'File size': 'File size',
  'Uploaded date time': 'Uploaded date time',
  'Uploaded by': 'Uploaded by',
  'Inspection management team comment': 'Inspection management team comment',
  'User name': 'User name',
  'Job title': 'Job title',
  Comment: 'Comment',
  'Uploaded date': 'Uploaded date',
  'Inspection history': 'Inspection history',
  'Inspection Ref.ID': 'Inspection Ref.ID',
  'From date': 'From date',
  'To date': 'To date',
  Place: 'Place',
  Type: 'Type',
  'Total no of findings': 'Total no of findings',
  'Total no of open findings': 'Total no of open findings',
  Export: 'Export',
  'Send mail': 'Send mail',
  'Ref.ID': 'Ref.ID',
  'Global status': 'Global status',
  Location: 'Location',
  'Inspector time off': 'Inspector time off',
  'Inspectors scheduler': 'Inspectors scheduler',
  'Time off information': 'Time off information',
  Search: 'Search',
  Username: 'Username',
  Description: 'Description',
  Duration: 'Duration',
  'Clear all': 'Clear all',
  'Zip files': 'Zip files',
  'Zip file': 'Zip file',
  Add: 'Add',
  'Total size': 'Total size',
  'Enter comment': 'Enter comment',
  'Commented date': 'Commented date',
  'Commented by': 'Commented by',
  'Add comment': 'Add comment',
  'Updated date': 'Updated date',
  'User assignment': 'User assignment',
  'Are you sure you want to': 'Are you sure you want to',
};
