export const PORT_FIELDS_LIST = {
  Action: 'Action',
  'Port code': 'Port code',
  'Port name': 'Port name',
  'Port type': 'Port type',
  Country: 'Country',
  'Bunkering port': 'Bunkering port',
  'Europe flag': 'Europe flag',
  Latitude: 'Latitude',
  Longitude: 'Longitude',
  Status: 'Status',
  'GMT offset': 'GMT offset',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  'Created by company': 'Created by company',
  System: 'System',
  Port: 'Port',
  'Port information': 'Port information',
  'Create New': 'Create New',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const PORT_FIELDS_DETAILS = {
  'Port code': 'Port code',
  'Port name': 'Port name',
  'Port type': 'Port type',
  Country: 'Country',
  'Bunkering port': 'Bunkering port',
  'Europe flag': 'Europe flag',
  Latitude: 'Latitude',
  'GMT offset': 'GMT offset',
  'Port information': 'Port information',
  N: 'N',
  B: 'B',
  S: 'S',
  DD: 'DD',
  'MM.SS': 'MM.SS',
  Longitude: 'Longitude',
  E: 'E',
  W: 'W',
  DDD: 'DDD',
  'Enter port code': 'Enter port code',
  'Enter port name': 'Enter port name',
  'Please select': 'Please select',
  Search: 'Search',
  Status: 'Status',
  'The port code is existed': 'The port code is existed',
  'The port name is existed': 'The port name is existed',
  'Latitude is not valid': 'Latitude is not valid',
  'Longitude is not valid': 'Longitude is not valid',
  'Port name must be between 2 and 20 characters.':
    'Port name must be between 2 and 20 characters.',
  'Port code must be between 2 and 20 characters.':
    'Port code must be between 2 and 20 characters.',
  Inland: 'Inland',
  Seaport: 'Seaport',
  'Dry port': 'Dry port',
  'Warm-water port': 'Warm-water port',
};
