export const RANK_DYNAMIC_LIST_FIELDS = {
  Action: 'Action',
  'Rank code': 'Rank code',
  'Rank name': 'Rank name',
  Type: 'Type',
  Description: 'Description',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  Status: 'Status',
  'Created by company': 'Created by company',
  Rank: 'Rank',
  Cancel: 'Cancel',
  Save: 'Save',
  'Save & New': 'Save & New',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  'Create New': 'Create New',
  Delete: 'Delete',
};

export const RANK_DYNAMIC_DETAIL_FIELDS = {
  'Rank code': 'Rank code',
  'Rank name': 'Rank name',
  'Enter rank code': 'Enter rank code',
  'Enter rank name': 'Enter rank name',
  'Enter description': 'Enter description',
  Type: 'Type',
  Description: 'Description',
  Status: 'Status',
  Shore: 'Shore',
  Ship: 'Ship',
  Active: 'Active',
  Inactive: 'Inactive',
  'Rank information': 'Rank information',
  Cancel: 'Cancel',
  Save: 'Save',
  'Save & New': 'Save & New',
  'The rank code is existed': 'The rank code is existed',
  'The rank name is existed': 'The rank name is existed',
};
