export const REPORT_TEMPLATE_MASTER_DYNAMIC_LIST_FIELDS = {
  Action: 'Action',
  'Serial number': 'Serial number',
  Entity: 'Entity',
  'Created date': 'Created date',
  'Created by user': 'Created by user',
  'Updated date': 'Updated date',
  'Updated by user': 'Updated by user',
  Status: 'Status',
  'Created by company': 'Created by company',
  'Create New': 'Create New',
  'Delete?': 'Delete?',
  Delete: 'Delete',
  Cancel: 'Cancel',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const REPORT_TEMPLATE_MASTER_DYNAMIC_DETAIL_FIELDS = {
  'General information': 'General information',
  Entity: 'Entity',
  Status: 'Status',
  'Version number': 'Version number',
  'Selected vessel type': 'Selected vessel type',
  'Selected inspection type': 'Selected inspection type',
  Selected: 'Selected',
  'Report template': 'Report template',
  Action: 'Action',
  'Serial number': 'Serial number',
  Topic: 'Topic',
  'Topic type': 'Topic type',
  'Print Option': 'Print Option',
  Type: 'Type',
  'Min score': 'Min score',
  'Max score': 'Max score',
  'S.No': 'S.No',
  'User Name': 'User Name',
  'Job Title': 'Job Title',
  'Uploaded Date': 'Uploaded Date',
  'User history section': 'User history section',
  Back: 'Back',
  Edit: 'Edit',
  Delete: 'Delete',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  'This field is required': 'This field is required',
  'Confirmation?': 'Confirmation?',
  'Are you sure you want to proceed with this action?':
    'Are you sure you want to proceed with this action?',
  Cancel: 'Cancel',
  Confirm: 'Confirm',
  'Enter version number': 'Enter version number',
  'Please select': 'Please select',
  'Select all': 'Select all',
  'Vessel type': 'Vessel type',
  'Inspection types': 'Inspection types',
  'Add header': 'Add header',
  'Edit header': 'Edit header',
  'Add sub-header': 'Add sub-header',
  'Edit sub-header': 'Edit sub-header',
  'Choose template': 'Choose template',
  Save: 'Save',
  'Save & New': 'Save & New',
  'Min score must be greater than 0': 'Min score must be greater than 0',
  'Min score must be smaller than 30': 'Min score must be smaller than 30',
  'Max score must be greater than 0': 'Max score must be greater than 0',
  'Min score must be smaller than max score':
    'Min score must be smaller than max score',
  'Max score must be greater than min score':
    'Max score must be greater than min score',
  'Enter topic': 'Enter topic',
  'Enter min score': 'Enter min score',
  'Enter max score': 'Enter max score',
  'Print option': 'Print option',
  'Max score must be smaller than 30': 'Max score must be smaller than 30',
  'Version template': 'Version template',
  'Choose version template': 'Choose version template',
  'Version number existed. Confirm to increase version number':
    'Version number existed. Confirm to increase version number',
  'Inspection type code': 'Inspection type code',
  'Inspection type name': 'Inspection type name',
  '#': '#',
  'Inspection type': 'Inspection type',
};
