export const LIST_REPORT_OF_FINDING_DYNAMIC_FIELDS = {
  'Ref.ID': 'Ref.ID',
  Entity: 'Entity',
  'Fleet name': 'Fleet name',
  'Vessel name': 'Vessel name',
  'Vessel type': 'Vessel type',
  Company: 'Company',
  Department: 'Department',
  Flag: 'Flag',
  'Inspection type': 'Inspection type',
  'Lead inspection name': 'Lead inspection name',
  'Total No.of findings': 'Total no of findings',
  'Total No.of NC': 'Total No.of NC',
  'Total No.of observation': 'Total No.of observation',
  'Inspection S.No': 'Inspection S.No',
  'Inspection Ref.ID': 'Inspection Ref.ID',
  'S.No': 'S.No',
  'Created date': 'Created date',
  Status: 'Status',
  'Global status': 'Global status',
  'Created by company': 'Created by company',
  'Revoke/ Recall': 'Revoke/ Recall',
};

export const DETAIL_REPORT_OF_FINDING_DYNAMIC_FIELDS = {
  'General information': 'General information',
  'Office comment': 'Office comment',
  'Enter comment': 'Enter comment',
  'Main category': 'Main category',
  'Company name': 'Company name',
  'Checklist name': 'Checklist name',
  Attach: 'Attach',
  'Reference number': 'Reference number',
  Checklist: 'Checklist',
  Department: 'Department',
  'Report of finding input fields': 'Report of finding input fields',
  'Is significant': 'Is significant',
  'Import excel': 'Import excel',
  'Verified and closed': 'Verified and closed',
  Pending: 'Pending',
  'Inspection number': 'Inspection number',
  'Overriding closure': 'Overriding closure',
  'Checklist no': 'Checklist no',
  'Vessel name': 'Vessel name',
  Reason: 'Reason',
  'Enter reason': 'Enter reason',
  Hold: 'Hold',
  'Total number of NC findings': 'Total number of NC findings',
  CAR: 'CAR',
  CAP: 'CAP',
  'Follow up Ref.ID': 'Follow up Ref.ID',
  'NC and CAR of previous inspection': 'NC and CAR of previous inspection',
  'Vessel manager': 'Vessel manager',
  'Load sheet': 'Load sheet',
  Reset: 'Reset',
  'Checklist view': 'Checklist view',
  Reassign: 'Reassign',
  'CAR reference': 'CAR reference',
  'Add comment': 'Add comment',
  'CAP status': 'CAP status',
  'CAP target date': 'CAP target date',
  'Car action request table': 'Car action request table',
  'Workflow progress': 'Workflow progress',
  Back: 'Back',
  'Please select': 'Please select',
  'Inspection type': 'Inspection type',
  'Global status': 'Global status',
  'Lead inspector name': 'Lead inspector name',
  'Inspector name': 'Inspector name',
  'Actual inspection from port': 'Actual inspection from port',
  'Actual inspection to port': 'Actual inspection to port',
  'Planned from date': 'Planned from date',
  'Ref.ID': 'Ref.ID',
  'Planned to date': 'Planned to date',
  'Findings details': 'Findings details',
  'Second category': 'Second category',
  'VIQ category': 'VIQ category',
  Findings: 'Findings',
  'Findings remarks': 'Findings remarks',
  'Rectified on board': 'Rectified on board',
  Attachments: 'Attachments',
  'Total no of findings': 'Total no of findings',
  'Total no of non conformity': 'Total no of non conformity',
  'Total no of observation': 'Total no of observation',
  Memo: 'Memo',
  'Report of findings': 'Report of findings',
  'Export template': 'Export template',
  'Import template': 'Import template',
  'Input fields': 'Input fields',
  Action: 'Action',
  'S.No': 'S.No',
  'User assignment': 'User assignment',
  'Findings comments': 'Findings comments',
  'Enter reference': 'Enter reference',
  'Findings type': 'Findings type',
  'Corrective action request': 'Corrective action request',
  'CAR S.No': 'CAR S.No',

  'CAR status': 'CAR status',
  'Inspection management team comment': 'Inspection management team comment',
  'Enter findings': 'Enter findings',
  'Enter findings remarks': 'Enter findings remarks',
  Comment: 'Comment',
  'Commented by': 'Commented by',
  'Job title': 'Job title',
  'Commented date': 'Commented date',
  'User history section': 'User history section',
  'Select excel file': 'Select excel file',
  'Data field': 'Data field',
  'Select sheet': 'Select sheet',
  'Row index': 'Row index',
  'Column index': 'Column index',
  'First row as header': 'First row as header',
  'Column name': 'Column name',
  'Excel index': 'Excel index',
  'Row no from': 'Row no from',
  'Row no to': 'Row no to',
  Cancel: 'Cancel',
  Upload: 'Upload',
  'Are you sure you want to review?': 'Are you sure you want to review?',
  'Are you sure you want to close out?': 'Are you sure you want to close out?',
  'Are you sure you want to reassign?': 'Are you sure you want to reassign?',
};
