export const SECOND_CATEGORY_DYNAMIC_LIST_FIELD = {
  'Second category code': 'Second category code',
  'Second category name': 'Second category name',
  SecAcronym: 'SecAcronym',
  Description: 'Description',
  Status: 'Status',
  Active: 'Active',
  Inactive: 'Inactive',
  'Second category information': 'Second category information',
  Action: 'Action',
  'Updated user': 'Updated user',
  'Updated date': 'Updated date',
  'Created user': 'Created user',
  'Created by company': 'Created by company',
  'Created date': 'Created date',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
  Delete: 'Delete',
  Cancel: 'Cancel',
  'Create New': 'Create New',
};

export const SECOND_CATEGORY_DYNAMIC_DETAIL_FIELD = {
  'Second Category Code': 'Second Category Code',
  'Second Category Name': 'Second Category Name',
  SecAcronym: 'SecAcronym',
  Description: 'Description',
  Status: 'Status',
  Active: 'Active',
  Inactive: 'Inactive',
  'Second category information': 'Second category information',
  'Enter second category code': 'Enter second category code',
  'Enter second category name': 'Enter second category name',
  'Enter description': 'Enter description',
  'Second category code': 'Second category code',
  'Second category name': 'Second category name',
  'Enter SecAcronym': 'Enter SecAcronym',
  Cancel: 'Cancel',
  Save: 'Save',
  'Save & New': 'Save & New',
};
