export const USER_MANAGEMENT_DYNAMIC_LIST_FIELDS = {
  Action: 'Action',
  'First name': 'First name',
  'Last name': 'Last name',
  Email: 'Email',
  Phone: 'Phone',
  'Job title': 'Job title',
  Gender: 'Gender',
  Nationality: 'Nationality',
  Country: 'Country',
  'State/ Province': 'State/ Province',
  'Town/ City': 'Town/ City',
  Address: 'Address',
  'Post code': 'Post code',
  Status: 'Status',
  Company: 'Company',
};

export const USER_MANAGEMENT_DYNAMIC_DETAIL_FIELDS = {
  'User information': 'User information',
  'Role and permission': 'Role and permission',
  Gender: 'Gender',
  'Password must contain': 'Password must contain',
  'Available area': 'Available area',
  Password: 'Password',
  'Inspector detail': 'Inspector detail',
  Information: 'Information',
  Title: 'Title',
  'Email is existed': 'Email is existed',
  'Subscription company': 'Subscription company',
  'User company': 'User company',
  'Select your avatar': 'Select your avatar',
  Browse: 'Browse',
  'Enter first name': 'Enter first name',
  'First name': 'First name',
  'Last name': 'Last name',
  'Enter last name': 'Enter last name',
  'Job title': 'Job title',
  'Enter job title': 'Enter job title',
  Nationality: 'Nationality',
  'Selected cities': 'Selected cities',
  Status: 'Status',
  Email: 'Email',
  'Enter email': 'Enter email',
  'Enter phone number': 'Enter phone number',
  'Phone number': 'Phone number',
  'Enter secondary phone number': 'Enter secondary phone number',
  'Secondary phone number': 'Secondary phone number',
  Male: 'Male',
  Female: 'Female',
  'Date of birth': 'Date of birth',
  Country: 'Country',
  'State/ Province': 'State/ Province',
  'Town/ City': 'Town/ City',
  'Enter town/city': 'Enter town/city',
  'Enter address': 'Enter address',
  'Enter address line 2': 'Enter address line 2',
  'Address line 2': 'Address line 2',
  'Enter post code': 'Enter post code',
  'Post code': 'Post code',
  'Selected division': 'Selected division',
  'Business division': 'Business division',
  'Copy password success': 'Copy password success',
  'Enter your password': 'Enter your password',
  'Confirm password': 'Confirm password',
  'Enter confirm password': 'Enter confirm password',
  Address: 'Address',
  'Auto generate': 'Auto generate',
  'Minimum 8-20 characters': 'Minimum 8-20 characters',
  'At least 1 number': 'At least 1 number',
  'At least 1 special character': 'At least 1 special character',
  'Please fill in your confirmation password':
    'Please fill in your confirmation password',
  'At least 1 lower case and upper case letter':
    'At least 1 lower case and upper case letter',
  Selected: 'Selected',
  'Reset password': 'Reset password',
  'New password': 'New password',
  'Selected role': 'Selected role',
  'Clear all': 'Clear all',
  'Add more +': 'Add more +',
  'Country is existed': 'Country is existed',
  'No preference': 'No preference',
  'Neutral preference': 'Neutral preference',
  'Strong preference': 'Strong preference',
  'Selected country': 'Selected country',
  Port: 'Port',
  'Port code': 'Port code',
  'Port name': 'Port name',
  'Add more': 'Add more',
  Edit: 'Edit',
  ports: 'ports',
  preference: 'preference',
  Position: 'Position',
  'Enter position': 'Enter position',
  'Company name': 'Company name',
  'Enter company name': 'Enter company name',
  'Start date': 'Start date',
  'Enter start date': 'Enter start date',
  'Till date': 'Till date',
  'End date': 'End date',
  Action: 'Action',
  'S.No': 'S.No',
  Type: 'Type',
  'License name': 'License name',
  'Issued by': 'Issued by',
  'Issue country': 'Issue country',
  'Verified by': 'Verified by',
  'Verified date time': 'Verified date time',
  Present: 'Present',
  Experience: 'Experience',
  'Certification name': 'Certification name',
  'Licenses certification': 'Licenses certification',
  'Enter license/certification name': 'Enter license/certification name',
  'Enter issued by': 'Enter issued by',
  'Issued date': 'Issued date',
  'Expiry date': 'Expiry date',
  'Inspection type': 'Inspection type',
  'Service provided': 'Service provided',
  'You have updated successfully': 'You have updated successfully',
  'Something went wrong!': 'Something went wrong!',
  Verified: 'Verified',
  at: 'at',
  'Provided inspection': 'Provided inspection',
  'The password confirmation does not match':
    'The password confirmation does not match',
  'Document type': 'Document type',
  'Passport/Visa number': 'Passport/Visa number',
  'Date of issue': 'Date of issue',
  'Date of expiry': 'Date of expiry',
  number: 'number',
  Enter: 'Enter',
  'You have created successfully': 'You have created successfully',
  'You have deleted successfully': 'You have deleted successfully',
  'Travel document': 'Travel document',
  'Enter passport/ VISA number': 'Enter passport/ VISA number',
  'Country of issue': 'Country of issue',
  'Enter issue place': 'Enter issue place',
  'Issue place': 'Issue place',
  'Account information': 'Account information',
  'Minimum length is 5 characters': 'Minimum length is 5 characters',
  'Maximum length is 15 characters': 'Maximum length is 15 characters',
  'Current password': 'Current password',
  'Enter current password': 'Enter current password',
  'Your password you entered is the same with your current password. Please re-enter the different password':
    'Your password you entered is the same with your current password. Please re-enter the different password',
  pass: 'pass',
  Profile: 'Profile',
  'Sign out': 'Sign out',
  'Edit User Profile': 'Edit User Profile',
  'Last login': 'Last login',
};
