export const VESSEL_LIST_DYNAMIC_FIELDS = {
  Action: 'Action',
  'IMO number': 'IMO number',
  'Vessel name': 'Vessel name',
  'Vessel code': 'Vessel code',
  Flag: 'Flag',
  'Vessel type': 'Vessel type',
  'Business division': 'Business division',
  'DOC holder': 'DOC holder',
  Status: 'Status',
  'Created by company': 'Created by company',
};

export const VESSEL_DETAIL_DYNAMIC_FIELDS = {
  'Select an image': 'Select an image',
  Browser: 'Browser',
  'Basic information': 'Basic information',
  'IMO number': 'IMO number',
  'Vessel name': 'Vessel name',
  'User can use decimal point. User can enter up to 2 numbers after the decimal point. Example: 145.26':
    'User can use decimal point. User can enter up to 2 numbers after the decimal point. Example: 145.26',
  'Vessel code': 'Vessel code',
  'Charterer name': 'Charterer name',
  Flag: 'Flag',
  'Enter LBP (m)': 'Enter LBP (m)',
  'Charterer information': 'Charterer information',
  'Enter LOA (m)': 'Enter LOA (m)',
  'Enter height (m)': 'Enter height (m)',
  Remark: 'Remark',
  'Enter charterer name': 'Enter charterer name',
  'Enter remark': 'Enter remark',
  'From date': 'From date',
  'Enter depth (m)': 'Enter depth (m)',
  'To date': 'To date',
  'Vessel owner information': 'Vessel owner information',
  'DOC holder information': 'DOC holder information',
  'DOC holder code': 'DOC holder code',
  'DOC holder name': 'DOC holder name',
  QA: 'QA',
  'Responsible party': 'Responsible party',
  Inspection: 'Inspection',
  'Enter max draft (Summer) (m)': 'Enter max draft (Summer) (m)',
  'Vessel type': 'Vessel type',
  'Selected cities': 'Selected cities',
  Country: 'Country',
  'Enter vessel name': 'Enter vessel name',
  'Enter breath (m)': 'Enter breath (m)',
  'CIMO number': 'CIMO number',
  'Enter light ship': 'Enter light ship',
  'Enter TEU capacity': 'Enter TEU capacity',
  'Enter vessel code': 'Enter vessel code',
  'Enter shipyard name': 'Enter shipyard name',
  'Enter official number': 'Enter official number',
  'Enter class number': 'Enter class number',
  'Enter hull number': 'Enter hull number',
  'Enter NRT': 'Enter NRT',
  'Enter fleet': 'Enter fleet',
  'Enter dead weight (Summer)': 'Enter dead weight (Summer)',
  'Enter call sign': 'Enter call sign',
  'Call sign': 'Call sign',
  'Enter IMO number': 'Enter IMO number',
  'Selected vessel type': 'Selected vessel type',
  'Selected classification society': 'Selected classification society',
  'Selected business division': 'Selected business division',
  'Business division': 'Business division',
  'Vessel Type': 'Vessel Type',
  'Date built': 'Date built',
  Age: 'Age',
  'Shipyard name': 'Shipyard name',
  'Enter GRT': 'Enter GRT',
  'Shipyard country': 'Shipyard country',
  'Official number': 'Official number',
  'Classification society': 'Classification society',
  'Class number': 'Class number',
  'Hull number': 'Hull number',
  Fleet: 'Fleet',
  Status: 'Status',
  'Management/Ownership': 'Management/Ownership',
  'You can add management / charterer / owner companies for vessel in this section.':
    'You can add management / charterer / owner companies for vessel in this section.',
  Note: 'Note',
  'If you cannot find companies you want to add, then please ':
    'If you cannot find companies you want to add, then please ',
  'Create new company': 'Create new company',
  'DOC Holder': 'DOC Holder',
  Charterer: 'Charterer',
  'Vessel owner': 'Vessel owner',
  'Add New': 'Add New',
  Action: 'Action',
  'S.No': 'S.No',
  'CIMO Number': 'CIMO Number',
  'Responsible party (Inspection)': 'Responsible party (Inspection)',
  'Responsible party (QA)': 'Responsible party (QA)',
  'Charterer type': 'Charterer type',
  'Charterer code': 'Charterer code',
  'Owner name': 'Owner name',
  'Owner code': 'Owner code',
  'Detailed information': 'Detailed information',
  'Dead weight (Summer)': 'Dead weight (Summer)',
  GRT: 'GRT',
  NRT: 'NRT',
  'TEU capacity': 'TEU capacity',
  'Max draft (Summer) (m)': 'Max draft (Summer) (m)',
  'Light ship': 'Light ship',
  Dimension: 'Dimension',
  'LOA (m)': 'LOA (m)',
  'LBP (m)': 'LBP (m)',
  'Breath (m)': 'Breath (m)',
  'Height (m)': 'Height (m)',
  'Depth (m)': 'Depth (m)',
  'Crew information': 'Crew information',
  'Crew nationality': 'Crew nationality',
  'Crew grouping': 'Crew grouping',
  Officers: 'Officers',
  Rating: 'Rating',
  'i-Nautix specific feature': 'i-Nautix specific feature',
  'Customer restricted': 'Customer restricted',
  'Blacklist on MOU website': 'Blacklist on MOU website',
  Yes: 'Yes',
  No: 'No',
};
