export const VIQ_FIELDS_LIST = {
  Action: 'Action',
  'Ref.No': 'Ref.No',
  Type: 'Type',
  'VIQ vessel type': 'VIQ vessel type',
  'Vessel Inspection Questionnaires': 'Vessel Inspection Questionnaires',
  Status: 'Status',
  'Create New': 'Create New',
  'Created by company': 'Created by company',
  'Delete?': 'Delete?',
  'Confirmation?': 'Confirmation?',
  'Are you sure you want to proceed with this action?':
    'Are you sure you want to proceed with this action?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const VIQ_FIELDS_DETAILS = {
  Action: 'Action',
  'VIQ information': 'VIQ information',
  'Add More': 'Add More',
  Type: 'Type',
  'VIQ vessel type': 'VIQ vessel type',
  'User defined version no.': 'User defined version no.',
  'Enter user defined version no.': 'Enter user defined version no.',
  'Vessel Inspection Questionnaires': 'Vessel Inspection Questionnaires',
  Status: 'Status',
  Active: 'Active',
  Inactive: 'Inactive',
  'VIQ main category': 'VIQ main category',
  'Main reference no.': 'Main reference no.',
  'Sub category number': 'Sub category number',
  'Main category name': 'Main category name',
  'Sub category name': 'Sub category name',
  'The main reference no is existed': 'The main reference no is existed',
  'The main category name is existed': 'The main category name is existed',
  'Enter main reference no.': 'Enter main reference no.',
  'Enter main category name': 'Enter main category name',
  'VIQ sub category': 'VIQ sub category',
  'Main Category Name': 'Main Category Name',
  'Sub Reference No.': 'Sub Reference No.',
  'Enter sub reference name': 'Enter sub reference name',
  'Sub Category Name': 'Sub Category Name',
  Questions: 'Questions',
  Guidance: 'Guidance',
  'Potential Risk': 'Potential Risk',
  'Second sub category number': 'Second sub category number',
  'VIQ second sub category': 'VIQ second sub category',
  'Second sub reference no.': 'Second sub reference no.',
  'Enter sub reference no.': 'Enter sub reference no.',
  'Second sub category name': 'Second sub category name',
  'Enter second sub category name': 'Enter second sub category name',
  'Potential risk': 'Potential risk',
  'Enter questions': 'Enter questions',
  'Enter guidance': 'Enter guidance',
  'Please select': 'Please select',
  'This field is required': 'This field is required',
  'Error message?': 'Error message?',
  'Please add VIQ main category and sub category':
    'Please add VIQ main category and sub category',
  'Add sub category': 'Add sub category',
  'Add second sub category': 'Add second sub category',
  'Add main category': 'Add main category',
  'Edit sub category': 'Edit sub category',
  'Edit second sub category': 'Edit second sub category',
  'Edit main category': 'Edit main category',
  'Delete?': 'Delete?',
  'Confirmation?': 'Confirmation?',
  'You need at least one subcategory and question in main category':
    'You need at least one subcategory and question in main category',
  'The sub reference no is existed': 'The sub reference no is existed',
  'Sub reference no.': 'Sub reference no.',
  'Enter sub category name': 'Enter sub category name',
  'The second sub reference no is existed':
    'The second sub reference no is existed',
};
