export const WORK_FLOW_FIELDS_LIST = {
  Action: 'Action',
  Description: 'Description',
  Status: 'Status',
  'Created by company': 'Created by company',
  'Version number': 'Version number',
  'WorkFlow Configuration': 'WorkFlow Configuration',
  Planning: 'Planning',
  'Inspection checklist template': 'Inspection checklist template',
  'Report of finding': 'Report of finding',
  'Inspection report': 'Inspection report',
  'CAR/CAP': 'CAR/CAP',
  Incidents: 'Incidents',
  'Self assessment': 'Self assessment',
  'Create New': 'Create New',
  'Delete?': 'Delete?',
  'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.':
    'Are you sure you want to delete this record? This action cannot be undone and you will not be able to recover any data.',
};

export const WORK_FLOW_FIELDS_DETAILS = {
  'Workflow type': 'Workflow type',
  Description: 'Description',
  Status: 'Status',
  Creator: 'Creator',
  Approver: 'Approver',
  Acceptor: 'Acceptor',
  Reviewer: 'Reviewer',
  Publisher: 'Publisher',
  'Owner/manager': 'Owner/manager',
  creator: 'creator',
  approver: 'approver',
  acceptor: 'acceptor',
  reviewer: 'reviewer',
  publisher: 'publisher',
  'owner/manager': 'owner/manager',
  Selected: 'Selected',
  'Clear all': 'Clear all',
  // 'Any users in the group can claim the permission as creator': 'Any users in the group can claim the permission as creator',
  // 'Any users in the group can claim the permission as approver': 'Any users in the group can claim the permission as approver',
  // 'Any users in the group can claim the permission as acceptor': 'Any users in the group can claim the permission as acceptor',
  // 'Any users in the group can claim the permission as owner/manager': 'Any users in the group can claim the permission as owner/manager',
  'Close out': 'Close out',
  'Please select': 'Please select',
  'Enter description': 'Enter description',
  'Internal audit report': 'Internal audit report',
  'First Reviewer': 'First Reviewer',
  'Second Reviewer': 'Second Reviewer',
  'Third Reviewer': 'Third Reviewer',
  'Fourth Reviewer': 'Fourth Reviewer',
  'Fifth Reviewer': 'Fifth Reviewer',
  'Verification creator': 'Verification creator',
  'Confirmation?': 'Confirmation?',
  'Are you sure you want to proceed with this action?':
    'Are you sure you want to proceed with this action?',
  'Any users in the group can claim the permission as':
    'Any users in the group can claim the permission as',
  // 'Any users in the group can claim the permission as first reviewer': 'Any users in the group can claim the permission as first reviewer',
  // 'Anys in the group can claim the permission as fifth reviewer': 'Any users in the group can claim the permission as fifth reviewer',
  // 'Any user users in the group can claim the permission as second reviewer': 'Any users in the group can claim the permission as second reviewer',
  // 'Any users in the group can claim the permission as third reviewer': 'Any users in the group can claim the permission as third reviewer',
  // 'Any users in the group can claim the permission as fourth reviewer': 'Any users in the group can claim the permission as fourth reviewer',
  // 'Any users in the group can claim the permission as CAP creator': 'Any users in the group can claim the permission as CAP creator',
  // 'Any users in the group can claim the permission as CAP reviewer': 'Any users in the group can claim the permission as CAP reviewer',
  // 'Any users in the group can claim the permission as Verification creator': 'Any users in the group can claim the permission as Verification creator'
};
