import { all, fork } from 'redux-saga/effects';
import SelfAssessmentSaga from 'pages/self-assessment/store/saga';
import CargoSaga from 'pages/cargo/store/saga';
import PlanDrawingSaga from 'pages/plan-drawing/store/saga';
import CargoTypeSaga from 'pages/cargo-type/store/saga';
import TransferTypeMasterSaga from 'pages/transfer-type/store/saga';
import VesselScreeningSaga from 'pages/vessel-screening/store/saga';
import vesselIncidentInvestigationSaga from 'pages/vessel-screening/store/vessel-incident-investigation.saga';

import vesselOtherTechRecordsSaga from 'pages/vessel-screening/store/vessel-other-tech-records.saga';
import vesselPortStateControlSaga from 'pages/vessel-screening/store/vessel-port-state-control.saga';
import vesselClassDispensationsSaga from 'pages/vessel-screening/store/vessel-class-dispensations.saga';
import IncidentsSaga from 'pages/incidents/store/saga';

import vesselMaintenancePerformanceSaga from 'pages/vessel-screening/store/vessel-maintenance-performance.saga';
// START_NEW_PAGE
import ValueManagementMasterSaga from 'pages/value-management/store/saga';
// END_NEW_PAGE
import VesselSummarySaga from 'pages/vessel-screening/store/vessel-summary.saga';
import VesselInternalInspectionSaga from 'pages/vessel-screening/store/vessel-internal-inspection.saga';
import CompanyTypeSaga from 'pages/company-type/store/saga';
import VesselExternalInspectionSaga from 'pages/vessel-screening/store/vessel-external-inspection.saga';
import vesselSurveysClassInfoSaga from 'pages/vessel-screening/store/vessel-surveys-class-info.saga';
import vesselDryDockingSaga from 'pages/vessel-screening/store/vessel-dry-docking.saga';
import VesselInjuriesSafetySaga from 'pages/vessel-screening/store/vessel-injuries-safety.saga';
import VesselOtherSMSSaga from 'pages/vessel-screening/store/vessel-other-sms.saga';
import VesselPlanAndDrawingsSaga from 'pages/vessel-screening/store/vessel-plan-and-drawing.saga';
import authenticateSaga from './authenticate/authenticate.saga';

import roleAndPermissionSaga from './role/role.saga';
import userManagementSaga from './user/user.saga';
import vesselTypeSaga from './vessel-type/vessel-type.saga';
import authorityMasterSaga from './authority-master/authority-master.saga';
import auditTypeManagementSaga from './audit-type/audit-type.saga';
import fleetManagementSaga from './fleet/fleet.saga';
import companyManagementSaga from './company/company.saga';
import groupManagementSaga from './group/group.saga';
import vesselManagementSaga from './vessel/vessel.saga';
import charterOwnerManagementSaga from './charter-owner/charter-owner.saga';
import auditTimeTableManagementSaga from './audit-time-table/audit-time-table.saga';
import pscActionManagementSaga from './psc-action/psc-action.saga';
import ownerBusinessSaga from './owner-business/owner-business.saga';
import locationManagementSaga from './location/location.saga';
import shipDirectResponsibleManagementSaga from './ship-direct-responsible/ship-direct-responsible.saga';
import shipDepartmentManagementSaga from './ship-department/ship-department.saga';
import auditCheckListSaga from './audit-checklist/audit-checklist.saga';
import categorySaga from './category/category.saga';
import mainCategorySaga from './main-category/main-category.saga';
import reportOfFindingSaga from './report-of-finding/report-of-finding.saga';
import secondCategorySaga from './second-category/second-category.saga';
import riskFactorSaga from './risk-factor/risk-factor.saga';
import externalSaga from './external/external.saga';
import terminalSaga from './terminal/terminal.saga';
import thirdCategorySaga from './third-category/third-category.saga';
import topicSaga from './topic/topic.saga';
import shoreDepartmentSaga from './shore-department/shore-department.saga';
import shoreRankSaga from './shore-rank/shore-rank.saga';
import CDISaga from './cdi/cdi.saga';
import ReportTemplateSaga from './report-template/report-template.saga';
import ShipRankSaga from './ship-rank/ship-rank.saga';
import VIQSaga from './viq/viq.saga';
import PortSaga from './port/port.saga';
import DMSSaga from './dms/dms.saga';
import InspectionMappingSaga from './inspection-mapping/inspection-mapping.saga';
import PSCSaga from './psc-deficiency/psc-deficiency.saga';
import AuditInspectionWorkspaceSaga from './audit-inspection-workspace/audit-inspection-workspace.saga';
import PlanningAndRequestSaga from './planning-and-request/planning-and-request.saga';
import PlanningAndDrawingsSaga from './plans-and-drawings/plans-and-drawings.saga';
import InternalAuditReportSaga from './internal-audit-report/internal-audit-report.saga';
import DepartmentMasterSaga from './department-master/department-master.saga';
import RankMasterSaga from './rank-master/rank-master.saga';
import NatureOfFindingsMasterSaga from './nature-of-findings-master/nature-of-findings-master.saga';
import WorkFlowSaga from './work-flow/work-flow.saga';
import dashboardSaga from './dashboard/dashboard.saga';
import DeviceControlSaga from './device-control/device-control.saga';
import AppTypePropertySaga from './app-type-property/app-type-property.saga';
import CategoryMappingSaga from './category-mapping/category-mapping.saga';
import TemplateSaga from './template/template.saga';
import FocusRequestSaga from './focus-request/focus-request.saga';
import InspectorTimeOffSaga from './inspector-time-off/inspector-time-off.saga';
import inspectionFollowUpSaga from './inspection-follow-up/inspection-follow-up.saga';
import FeatureConfigSaga from './feature-config/feature-config.saga';
import MailManagementSaga from './mail-management/mail-management.saga';
import ElementMasterSaga from './element-master/element-master.saga';
import StandardMasterSaga from './standard-master/standard-master.saga';
import SurveyClassInfoSaga from './survey-class-info/survey-class-info.saga';
import DryDockingSaga from './dry-docking/dry-docking.saga';
import EventTypeMasterSaga from './event-type/event-type.saga';
import AttachmentKitSaga from './attachment-kit/attachment-kit.saga';
import IncidentTypeSaga from './incident-type/incident-type.saga';
import IssueNoteNoteSaga from './issue-note/issue-note.saga';
import ConditionOfClassAndPermissionSaga from './condition-of-class/condition-of-class.saga';
import IncidentInvestigationSaga from './incident-investigation/incident-investigation.saga';
import MaintenancePerformanceSaga from './maintenance-performance/maintenance-performance.saga';
import OtherTechnicalRecordsSaga from './other-technical-records/other-technical-records.saga';
import InjurySaga from './injury/injury.saga';
import InjuryMasterSaga from './injury-master/injury-master.saga';
import InjuryBodySaga from './injury-body/injury-body.saga';
import PlansAndDrawingSaga from './planning-and-drawings/planning-and-drawings.saga';
import SmsSaga from './sms/sms.saga';
import PortStateControlSaga from './port-state-control/port-state-control.saga';
import SailReportInspectionInternalSaga from './sail-report-inspection-internal/sail-report-inspection-internal.saga';
import SailReportingSummarySaga from './summary-sail-reporting/summary-sail-reporting.saga';
import MapViewSaga from '../pages/map-view/store/saga';
import PilotTerminalFeedbackSaga from '../pages/pilot-terminal-feedback/store/saga';
import CrewGroupingSaga from '../pages/crew-grouping/store/saga';
import DivisionSaga from '../pages/division/store/saga';
import DivisionMappingSaga from '../pages/division-mapping/store/saga';
import NotificationSaga from '../pages/notification/store/saga';
import RFCMasterSaga from '../pages/repeated-finding/store/saga';
import VoyageInfoMasterSaga from '../pages/vessel-screening/store/voyageInfo-store/voyage-info.saga';
import CountryMasterSaga from './country-master/country-master.saga';
import HomePageSaga from './home-page/home-page.saga';
import ModuleConfigurationSaga from './module-configuration/module-configuration.saga';
import DynamicSaga from './dynamic/dynamic.saga';
import WatchListSaga from './watch-list/watch-list.saga';

export default function* rootSaga() {
  try {
    yield all([fork(authenticateSaga)]);
    yield all([fork(roleAndPermissionSaga)]);
    yield all([fork(userManagementSaga)]);
    yield all([fork(vesselTypeSaga)]);
    yield all([fork(authorityMasterSaga)]);
    yield all([fork(auditTypeManagementSaga)]);
    yield all([fork(fleetManagementSaga)]);
    yield all([fork(companyManagementSaga)]);
    yield all([fork(MailManagementSaga)]);
    yield all([fork(groupManagementSaga)]);
    yield all([fork(inspectionFollowUpSaga)]);
    yield all([fork(vesselManagementSaga)]);
    yield all([fork(charterOwnerManagementSaga)]);
    yield all([fork(auditTimeTableManagementSaga)]);
    yield all([fork(pscActionManagementSaga)]);
    yield all([fork(ownerBusinessSaga)]);
    yield all([fork(locationManagementSaga)]);
    yield all([fork(shipDirectResponsibleManagementSaga)]);
    yield all([fork(shipDepartmentManagementSaga)]);
    yield all([fork(auditCheckListSaga)]);
    yield all([fork(topicSaga)]);
    yield all([fork(shoreRankSaga)]);
    yield all([fork(CDISaga)]);
    yield all([fork(categorySaga)]);
    yield all([fork(mainCategorySaga)]);
    yield all([fork(reportOfFindingSaga)]);
    yield all([fork(secondCategorySaga)]);
    yield all([fork(riskFactorSaga)]);
    yield all([fork(externalSaga)]);
    yield all([fork(terminalSaga)]);
    yield all([fork(thirdCategorySaga)]);
    yield all([fork(ReportTemplateSaga)]);
    yield all([fork(shoreDepartmentSaga)]);
    yield all([fork(PortSaga)]);
    yield all([fork(ShipRankSaga)]);
    yield all([fork(VIQSaga)]);
    yield all([fork(DMSSaga)]);
    yield all([fork(InspectionMappingSaga)]);
    yield all([fork(PSCSaga)]);
    yield all([fork(AuditInspectionWorkspaceSaga)]);
    yield all([fork(PlanningAndRequestSaga)]);
    yield all([fork(PlanningAndDrawingsSaga)]);
    yield all([fork(InternalAuditReportSaga)]);
    yield all([fork(DepartmentMasterSaga)]);
    yield all([fork(RankMasterSaga)]);
    yield all([fork(NatureOfFindingsMasterSaga)]);
    yield all([fork(WorkFlowSaga)]);
    yield all([fork(dashboardSaga)]);
    yield all([fork(DeviceControlSaga)]);
    yield all([fork(AppTypePropertySaga)]);
    yield all([fork(CategoryMappingSaga)]);
    yield all([fork(AttachmentKitSaga)]);
    yield all([fork(TemplateSaga)]);
    yield all([fork(FocusRequestSaga)]);
    yield all([fork(InspectorTimeOffSaga)]);
    yield all([fork(FeatureConfigSaga)]);
    yield all([fork(ElementMasterSaga)]);
    yield all([fork(StandardMasterSaga)]);
    yield all([fork(SurveyClassInfoSaga)]);
    yield all([fork(DryDockingSaga)]);
    yield all([fork(SelfAssessmentSaga)]);
    yield all([fork(EventTypeMasterSaga)]);
    yield all([fork(IncidentTypeSaga)]);
    yield all([fork(IssueNoteNoteSaga)]);
    yield all([fork(ConditionOfClassAndPermissionSaga)]);
    yield all([fork(IncidentInvestigationSaga)]);
    yield all([fork(MaintenancePerformanceSaga)]);
    yield all([fork(OtherTechnicalRecordsSaga)]);
    yield all([fork(InjurySaga)]);
    yield all([fork(InjuryMasterSaga)]);
    yield all([fork(InjuryBodySaga)]);
    yield all([fork(PlansAndDrawingSaga)]);
    yield all([fork(SmsSaga)]);
    yield all([fork(PortStateControlSaga)]);
    yield all([fork(SailReportInspectionInternalSaga)]);
    yield all([fork(CargoSaga)]);
    yield all([fork(CargoTypeSaga)]);
    // START_NEW_PAGE
    yield all([fork(ValueManagementMasterSaga)]);
    // END_NEW_PAGE
    yield all([fork(CompanyTypeSaga)]);
    yield all([fork(TransferTypeMasterSaga)]);
    yield all([fork(VesselScreeningSaga)]);
    yield all([fork(vesselMaintenancePerformanceSaga)]);
    yield all([fork(VesselInternalInspectionSaga)]);
    yield all([fork(VesselExternalInspectionSaga)]);
    yield all([fork(vesselOtherTechRecordsSaga)]);
    yield all([fork(vesselPortStateControlSaga)]);
    yield all([fork(vesselSurveysClassInfoSaga)]);
    yield all([fork(vesselDryDockingSaga)]);
    yield all([fork(vesselIncidentInvestigationSaga)]);
    yield all([fork(VesselInjuriesSafetySaga)]);
    yield all([fork(vesselClassDispensationsSaga)]);
    yield all([fork(VesselOtherSMSSaga)]);
    yield all([fork(VesselPlanAndDrawingsSaga)]);
    yield all([fork(IncidentsSaga)]);
    yield all([fork(SailReportingSummarySaga)]);
    yield all([fork(VesselSummarySaga)]);
    yield all([fork(MapViewSaga)]);
    yield all([fork(DivisionSaga)]);
    yield all([fork(DivisionMappingSaga)]);
    yield all([fork(PlanDrawingSaga)]);
    yield all([fork(PilotTerminalFeedbackSaga)]);
    yield all([fork(CrewGroupingSaga)]);
    yield all([fork(NotificationSaga)]);
    yield all([fork(RFCMasterSaga)]);
    yield all([fork(VoyageInfoMasterSaga)]);
    yield all([fork(CountryMasterSaga)]);
    yield all([fork(HomePageSaga)]);
    yield all([fork(ModuleConfigurationSaga)]);
    yield all([fork(DynamicSaga)]);
    yield all([fork(WatchListSaga)]);
  } catch (e) {
    // NOTED: use this log to display error of root saga
    // eslint-disable-next-line no-console
    console.log('Root saga error: ', e);
  }
}
