export enum USER_DATA_TABS {
  FOR_RENT = 'FORRENT',
  RENTALS = 'RENTALS',
  GALLERY = 'GALLERY',
  FAVORITE = 'FAVORITE',
  ORDERS = 'ORDERS',
}

export enum TYPE_CHANGE_PICTURE {
  COVER_PHOTO = 'COVER_PHOTO',
  COVER_AVATAR = 'COVER_AVATAR',
}

export enum SIZE_PICTURE_COVER_PHOTO {
  WIDTH = 1440,
  HEIGHT = 368,
}

export enum SIZE_PICTURE_AVATAR {
  WIDTH = 180,
  HEIGHT = 180,
}
