import moment from 'moment';

export const DATE_DEFAULT = [
  moment().startOf('month').subtract(3, 'months'),
  moment().endOf('day'),
];

export const DEFAULT_COL_DEF = {
  sortable: true,
  filter: true,
  floatingFilter: true,
  resizable: true,
  openByDefault: true,
  pivot: true,
  width: 200,
  minWidth: 45,
  enableRowGroup: true,
  getRowHeight: 20,
  // flex: 1,
};

export const DEFAULT_COL_DEF_TYPE_FLEX = {
  sortable: true,
  filter: true,
  floatingFilter: true,
  resizable: true,
  openByDefault: true,
  pivot: true,
  minWidth: 45,
  enableRowGroup: true,
  getRowHeight: 20,
  flex: 1,
};

export const DEFAULT_COL_DEF_TYPE_FLEX_QA = {
  sortable: true,
  filter: true,
  floatingFilter: true,
  resizable: true,
  openByDefault: true,
  pivot: true,
  minWidth: 200,
  enableRowGroup: true,
  getRowHeight: 20,
  flex: 1,
};

export const DEFAULT_LINE_HEIGHT = {
  lineHeight: 26,
  totalHeight: 275,
  totalRow: 5,
  defaultRow: 3,
  limitedRow: 1,
};

export const MODULE_TEMPLATE = {
  repeatedFindingCalculation: 'repeatedFindingCalculation',
  user: 'user',
  companyType: 'Company type',
  appTypeProperty: 'appTypeProperty',
  division: 'division',
  divisionMapping: 'divisionMapping',
  attachmentKit: 'attachmentKit',
  categoryMapping: 'categoryMapping',
  CharterOwner: 'CharterOwner',
  pilotTerminalFeedback: 'pilotTerminalFeedback',
  cargo: 'cargo',
  departmentMaster: 'departmentMaster',
  cdi: 'cdi',
  cargoType: 'cargoType',
  injuryBody: 'injuryBody',
  company: 'company',
  topic: 'topic',
  deviceControl: 'deviceControl',
  dms: 'dms',
  eventType: 'eventType',
  focusRequest: 'focusRequest',
  incidentType: 'incidentType',
  injuryMaster: 'injuryMaster',
  auditType: 'auditType',
  issueNote: 'issueNote',
  location: 'location',
  natureOfFindingsMaster: 'natureOfFindingsMaster',
  mainCategory: 'mainCategory',
  planDrawingMaster: 'planDrawingMaster',
  pscAction: 'pscAction',
  pscDeficiency: 'pscDeficiency',

  planningAndRequest: 'PlanningAndRequest',
  planningCompletedTab: 'PlanningCompletedTab',
  planningUnplannedTab: 'planningUnplannedTab',
  workflowPlanningTab: 'workflowPlanningTab',
  workflowAuditChecklistTab: 'workflowAuditChecklistTab',
  workflowReportFindingTab: 'workflowReportFindingTab',
  workflowInternalAuditReportTab: 'workflowInternalAuditReportTab',
  workflowCARCAPTab: 'workflowCARCAPTab',
  workflowSelfAssessmentTab: 'workflowSelfAssessmentTab',
  auditTimeTable: 'AuditTimeTable',
  auditInspectionWorkspace: 'AuditInspectionWorkspace',
  reportOfFindings: 'ReportOfFindings',
  internalAuditReport: 'InternalAuditReport',
  inspectionChecklistTemplate: 'inspectionChecklistTemplate',
  iWChecklistInformationTemplate: 'iWChecklistInformationTemplate',
  iWChecklistFindingSummaryTemplate: 'iWChecklistFindingSummaryTemplate',
  inspectionMapping: 'inspectionMappingTemplate',
  reportTemplateMaster: 'reportTemplateMasterTemplate',
  inspectionFollowUp: 'inspectionFollowUp',
  selfAssessmentTemplate: 'selfAssessmentTemplate',
  selfDeclarationTemplate: 'selfDeclarationTemplate',
  elementMaster: 'elementMasterTemplate',
  standardMaster: 'standardMasterTemplate',
  mailManagement: 'mailManagement',
  incidentInvestigation: 'incidentInvestigationTemplate',
  maintenancePerformance: 'maintenancePerformanceTemplate',
  otherRecord: 'otherRecordTemplate',
  dryDocking: 'dryDocking',
  remarkInspectionWorkspace: 'remarkInspectionWorkspace',
  conditionOfClass: 'conditionOfClassTemplate',
  surveyClassInfo: 'surveyClassInfoTemplate',
  plansAndDrawing: 'plansAndDrawingTemplate',
  portStateControl: 'portStateControlTemplate',
  inspectionHistorySummaryIWTemplate: 'inspectionHistorySummaryIWTemplate',
  otherInspectionsAndAudits: 'otherInspectionsAndAudits',
  sailReportInspectionInternal: 'sailReportInspectionInternal',
  sailReportInjuries: 'sailReportInjuries',
  sailReportOtherSMSRecords: 'sailReportOtherSMSRecords',
  sailReportInspectionExternal: 'sailReportInspectionExternal',
  cargoMasterTable: 'cargoMasterTableTemplate',
  vessel: 'vesselTemplate',
  viq: 'viq',
  vesselScreening: 'vesselScreeningTemplate',
  vesselScreeningIncident: 'vesselScreeningIncidentTemplate',
  vesselScreeningInspectionInternal: 'vesselScreeningInspectionInternal',
  vesselScreeningInspectionExternal: 'vesselScreeningInspectionExternal',
  vesselScreeningInjuries: 'vesselScreeningInjuries',
  vesselScreeningSurveyClass: 'vesselScreeningSurveyClass',
  vesselScreeningOtherSMSRecords: 'vesselScreeningOtherSMSRecords',
  vesselScreeningDryDocking: 'vesselScreeningDryDocking',
  vesselScreeningPSC: 'vesselScreeningPSC',
  vesselScreeningPilotTerminalFeedback: 'vesselScreeningPilotTerminalFeedback',
  vesselScreeningConditionOfClass: 'vesselScreeningConditionOfClass',
  selfAssessmentElementMaster: 'selfAssessmentElementMaster',
  vesselOtherTechnicalRecord: 'vesselOtherTechnicalRecord',
  vesselMaintenancePerformance: 'vesselMaintenancePerformance',
  vesselPlansAndDrawings: 'vesselPlansAndDrawings',
  roleAndPermissionTemplate: 'roleAndPermissionTemplate',
  incidentsTemplate: 'incidentsTemplate',
  incidentsDetailTemplate: 'incidentsDetailTemplate',
  sailGeneralReport: 'sailGeneralReport',
  sailSafetyEngagement: 'sailSafetyEngagementTemplate',
  vesselSafetyEngagement: 'vesselSafetyEngagementTemplate',
  vesselSafetyPilotTerminalFeedback: 'vesselSafetyPilotTerminalFeedback',
  crewGrouping: 'crewGrouping',
  port: 'port',
  rank: 'rank',
  riskFactor: 'riskFactor',
  secondCategory: 'seconCategory',
  terminal: 'terminal',
  thirdCategory: 'thirdCategory',
  vesselOwnerBusiness: 'vesselOwnerBusiness',
  timeOffManagement: 'timeOffManagement',
  vesselType: 'vesselType',
  transferType: 'transferType',
  valueManagement: 'valueManagement',
  planDrawings: 'planDrawings',
  reportTemplate: 'reportTemplate',
  userHistorySection: 'userHistorySection',
  auditChecklistManagementDetail: 'auditChecklistManagementDetail',
  tableAttachment: 'tableAttachment',
  tableOfficeComment: 'tableOfficeComment',
  inspectionHistory: 'inspectionHistory',
  tableHistory: 'tableHistory',
  tableHistorySection: 'tableHistorySection',
  reportTemplateTableHistory: 'reportTemplateTableHistory',
  auditCheckListGeneralInfoTableHistorySection:
    'auditCheckListGeneralInfoTableHistorySection',
  auditCheckListQuestionListFormTableAttachment:
    'auditCheckListQuestionListFormTableAttachment',
  openTaskInspectionChecklistTemplate: 'openTaskInspectionChecklistTemplates',
  openTaskReportOfFindingsTemplate: 'openTaskReportOfFindingsTemplate',
  openTaskInspectionReportsTemplate: 'openTaskInspectionReportsTemplate',
  planningAndRequestFormTableAttachment:
    'planningAndRequestFormTableAttachment',
  planningAndRequestFormTableOfficeComment:
    'planningAndRequestFormTableOfficeComment',
  planningAndRequestFormTableHistory: 'planningAndRequestFormTableHistory',
  planningAndRequestFormInspectionHistory:
    'planningAndRequestFormInspectionHistory',
  attachmentKitFormTableAttachment: 'attachmentKitFormTableAttachment',
  reportOfFindingFormTableHistory: 'reportOfFindingFormTableHistory',
  internalAuditReportInspectionHistoryTable:
    'internalAuditReportInspectionHistoryTable',
  inspectionInspectionMappingUserHistoryTemplate:
    'inspectionInspectionMappingUserHistoryTemplate',
  auditTimeTableTableAttachment: 'auditTimeTableTableAttachment',
  reportOfFindingTable: 'reportOfFindingTable',
  carActionReqTable: 'carActionReqTable',
  tableOfficeCommentNew: 'tableOfficeCommentNew',
  auditTimeTableTableHistory: 'auditTimeTableTableHistory',
  tableCheckListView: 'tableCheckListView',
  vesselRemainingValidity90sTemplate: 'vesselRemainingValidity90sTemplate',
  companyBlacklistedVesselTemplate: 'companyBlacklistedVesselTemplate',
  vesselHasRestrictedTemplate: 'vesselHasRestrictedTemplate',
  companyInspectionPlanTemplate: 'companyInspectionPlanTemplate',
  companyVesselSafetyScoreTemplate: 'companyVesselSafetyScoreTemplate',
  vesselGHGRatingTemplate: 'vesselGHGRatingTemplate',
  inspectionTimeTablesNotClosedOut: 'inspectionTimeTablesNotClosedOut',
  reportOfFindingsNotClosedOut: 'Report of findings not closed out',
  inspectionReportsNotClosedOut: 'Inspection reports not closed out',
  openNonConformity: 'Open non-conformity',
  openObservations: 'Open observations',
  openNonConformityAuditor: 'Open non-conformity auditor',
  openObservationsAuditor: 'Open observations auditor',
  inspectionTimeTablesNotClosedOutAuditor:
    'Inspection reports not closed out auditor',
  reportOfFindingsNotClosedOutAuditor:
    'Report of findings not closed out auditor',
  inspectionReportsNotClosedOutAuditor:
    'Inspection reports not closed out auditor',
  openNonConformityCompany: 'Open non-conformity company',
  openObservationsCompany: 'Open observations company',
  inspectionTimeTablesNotClosedOutCompany:
    'Inspection reports not closed out company',
  reportOfFindingsNotClosedOutCompany:
    'Report of findings not closed out company',
  upcomingAuditPlanVessel: 'Upcoming audit plans',
  upcomingReportVessel: 'Upcoming report vessel',
  upcomingReportVesselDetail: 'Upcoming report vessel',
  vesselAgeBelow14: 'vesselAgeBelow14',
  vesselAge15to29: 'vesselAge15to29',
  vesselAge30to44: 'vesselAge30to44',
  vesselAge45to99: 'vesselAge45to99',
  vesselAgeMoreThan99: 'vesselAgeMoreThan99',
  modalSelectVessel: 'modalSelectVessel',
  inspectionPlansNeedReviewingModal: 'Inspection plans need reviewing',
  columnInspectionTimeTableNotClosedOutSection:
    'Inspection time table not close out',
  calendarHomepage: 'calendarHomepage',
  modalOpenCar: 'Modal number of open car',
  modalHoldCap: 'Modal number of hold cap',
  modalPendingCap: 'Modal number of pending cap',
  modalDeniedCap: 'Modal number of denied cap',
  moduleConfigurationList: 'Module Configuration',
  labelOnModuleConfigList: 'Label on module config list ',
  openTaskPlanningModal: 'Open Task planning modal',
  watchList: 'Watch List',
  timeOffInformation: 'Time off information',
  choosePortIncident: 'Choose Port At Incidents',
  pscActionModal: 'PSC Action Modal',
  pscDeficiencyModal: 'PSC Deficiency Modal',
  incidents: 'incidents',
};

export const TYPE_TEMPLATE = {
  global: 'global',
  template: 'template',
};

export const TEXT_ACTION_TEMPLATE = {
  saveTemplate: 'Save template',
  saveAsTemplate: 'Save as template',
  deleteTemplate: 'Delete template',
  globalTemplate: 'Global template',
  distinctFilter: 'Distinct filter',
  conditionFilter: 'Condition filter',
  multipleFilter: 'Multiple filter',
  reset: 'Reset',
  excel: 'Excel',
  CSV: 'CSV',
  fullScreen: 'Full screen',
};

export const DATA_SPACE = ' ';

export const TYPE_LIST_TEMPLATE_2 = [
  MODULE_TEMPLATE.iWChecklistFindingSummaryTemplate,
  MODULE_TEMPLATE.planningCompletedTab,
];

export const TYPE_LIST_TEMPLATE_3 = [MODULE_TEMPLATE.planningUnplannedTab];

export const TYPE_LIST_TEMPLATE_4 = [
  MODULE_TEMPLATE.inspectionHistorySummaryIWTemplate,
];
