export const BREAD_CRUMB = {
  HOME_PAGE: 'HOME_PAGE',
  DASHBOARD: 'DASHBOARD',
  INSPECTION_DASHBOARD: 'INSPECTION_DASHBOARD',
  DASHBOARD_MASTER: 'DASHBOARD_MASTER',

  ROLE: 'ROLE',
  ROLE_AND_PERMISSION_CREATE: 'ROLE_AND_PERMISSION_CREATE',
  ROLE_AND_PERMISSION_DETAIL: 'ROLE_AND_PERMISSION_DETAIL',
  ROLE_AND_PERMISSION_EDIT: 'ROLE_AND_PERMISSION_EDIT',

  GROUP: 'GROUP',
  GROUP_CREATE: 'GROUP_CREATE',
  GROUP_EDIT: 'GROUP_EDIT',
  GROUP_DETAIL: 'GROUP_DETAIL',

  LOCATION: 'LOCATION',
  LOCATION_CREATE: 'LOCATION_CREATE',
  LOCATION_EDIT: 'LOCATION_EDIT',
  LOCATION_DETAIL: 'LOCATION_DETAIL',

  USER: 'USER',
  USER_CREATE: 'USER_CREATE',
  USER_DETAIL: 'USER_DETAIL',
  USER_EDIT: 'USER_EDIT',

  USER_PROFILE: 'USER_PROFILE',

  AUDIT_TYPE: 'AUDIT_TYPE',
  AUDIT_TYPE_CREATE: 'AUDIT_TYPE_CREATE',
  AUDIT_TYPE_DETAIL: 'AUDIT_TYPE_DETAIL',
  AUDIT_TYPE_EDIT: 'AUDIT_TYPE_EDIT',

  VESSEL_TYPE: 'VESSEL_TYPE',
  VESSEL_TYPE_CREATE: 'VESSEL_TYPE_CREATE',
  VESSEL_TYPE_DETAIL: 'VESSEL_TYPE_DETAIL',
  VESSEL_TYPE_EDIT: 'VESSEL_TYPE_EDIT',

  AUTHORITY_MASTER: 'AUTHORITY_MASTER',
  AUTHORITY_MASTER_CREATE: 'AUTHORITY_MASTER_CREATE',
  AUTHORITY_MASTER_DETAIL: 'AUTHORITY_MASTER_DETAIL',
  AUTHORITY_MASTER_EDIT: 'AUTHORITY_MASTER_EDIT',

  DIVISION: 'DIVISION',

  DIVISION_MAPPING: 'DIVISION_MAPPING',
  DIVISION_MAPPING_CREATE: 'DIVISION_MAPPING_CREATE',

  ATTACHMENT_KIT: 'ATTACHMENT_KIT',
  ATTACHMENT_KIT_CREATE: 'ATTACHMENT_KIT_CREATE',
  ATTACHMENT_KIT_EDIT: 'ATTACHMENT_KIT_EDIT',
  ATTACHMENT_KIT_DETAIL: 'ATTACHMENT_KIT_DETAIL',
  // START_NEW_PAGE
  VALUE_MANAGEMENT: 'VALUE_MANAGEMENT',
  // END_NEW_PAGE
  PLAN_DRAWING: 'PLAN_DRAWING',
  COMPANY_TYPE: 'COMPANY_TYPE',

  MAIL_MANAGEMENT: 'MAIL_MANAGEMENT',
  MAP_VIEW: 'MAP_VIEW',
  MAIL_MANAGEMENT_CREATE: 'MAIL_MANAGEMENT_CREATE',
  MAIL_MANAGEMENT_EDIT: 'MAIL_MANAGEMENT_EDIT',
  MAIL_MANAGEMENT_DETAIL: 'MAIL_MANAGEMENT_DETAIL',

  VESSEL: 'VESSEL',
  VESSEL_CREATE: 'VESSEL_CREATE',
  VESSEL_EDIT: 'VESSEL_EDIT',
  VESSEL_DETAIL: 'VESSEL_DETAIL',

  FLEET: 'FLEET',
  FLEET_CREATE: 'FLEET_CREATE',
  FLEET_DETAIL: 'FLEET_DETAIL',
  FLEET_EDIT: 'FLEET_EDIT',

  COMPANY: 'COMPANY',
  COMPANY_CREATE: 'COMPANY_CREATE',
  COMPANY_DETAIL: 'COMPANY_DETAIL',
  COMPANY_EDIT: 'COMPANY_EDIT',

  CHARTER_OWNER: 'CHARTER_OWNER',
  CHARTER_OWNER_CREATE: 'CHARTER_OWNER_CREATE',
  CHARTER_OWNER_DETAIL: 'CHARTER_OWNER_DETAIL',
  CHARTER_OWNER_EDIT: 'CHARTER_OWNER_EDIT',

  AUDIT_TIME_TABLE: 'AUDIT_TIME_TABLE',
  AUDIT_TIME_TABLE_CREATE: 'AUDIT_TIME_TABLE_CREATE',
  AUDIT_TIME_TABLE_DETAIL: 'AUDIT_TIME_TABLE_DETAIL',
  AUDIT_TIME_TABLE_EDIT: 'AUDIT_TIME_TABLE_EDIT',

  PSC_ACTION: 'PSC_ACTION',
  PSC_ACTION_CREATE: 'PSC_ACTION_CREATE',
  PSC_ACTION_DETAIL: 'PSC_ACTION_DETAIL',
  PSC_ACTION_EDIT: 'PSC_ACTION_EDIT',

  OWNER_BUSINESS: 'OWNER_BUSINESS',
  OWNER_BUSINESS_CREATE: 'OWNER_BUSINESS_CREATE',
  OWNER_BUSINESS_DETAIL: 'OWNER_BUSINESS_DETAIL',
  OWNER_BUSINESS_EDIT: 'OWNER_BUSINESS_EDIT',

  SHIP_DIRECT_RESPONSIBLE: 'SHIP_DIRECT_RESPONSIBLE',
  SHIP_DIRECT_RESPONSIBLE_CREATE: 'SHIP_DIRECT_RESPONSIBLE_CREATE',
  SHIP_DIRECT_RESPONSIBLE_DETAIL: 'SHIP_DIRECT_RESPONSIBLE_DETAIL',
  SHIP_DIRECT_RESPONSIBLE_EDIT: 'SHIP_DIRECT_RESPONSIBLE_EDIT',

  SHIP_DEPARTMENT: 'SHIP_DEPARTMENT',
  SHIP_DEPARTMENT_CREATE: 'SHIP_DEPARTMENT_CREATE',
  SHIP_DEPARTMENT_DETAIL: 'SHIP_DEPARTMENT_DETAIL',
  SHIP_DEPARTMENT_EDIT: 'SHIP_DEPARTMENT_EDIT',

  MODULE_MANAGEMENT: 'MODULE_MANAGEMENT',

  CATEGORY: 'CATEGORY',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_DETAIL: 'CATEGORY_DETAIL',
  CATEGORY_EDIT: 'CATEGORY_EDIT',

  MAIN_CATEGORY: 'MAIN_CATEGORY',
  MAIN_CATEGORY_CREATE: 'MAIN_CATEGORY_CREATE',
  MAIN_CATEGORY_DETAIL: 'MAIN_CATEGORY_DETAIL',
  MAIN_CATEGORY_EDIT: 'MAIN_CATEGORY_EDIT',

  SECOND_CATEGORY: 'SECOND_CATEGORY',
  SECOND_CATEGORY_CREATE: 'SECOND_CATEGORY_CREATE',
  SECOND_CATEGORY_DETAIL: 'SECOND_CATEGORY_DETAIL',
  SECOND_CATEGORY_EDIT: 'SECOND_CATEGORY_EDIT',

  RISK_FACTOR: 'RISK_FACTOR',
  RISK_FACTOR_CREATE: 'RISK_FACTOR_CREATE',
  RISK_FACTOR_DETAIL: 'RISK_FACTOR_DETAIL',
  RISK_FACTOR_EDIT: 'RISK_FACTOR_EDIT',

  TERMINAL: 'TERMINAL',
  TERMINAL_CREATE: 'TERMINAL_CREATE',
  TERMINAL_DETAIL: 'TERMINAL_DETAIL',
  TERMINAL_EDIT: 'TERMINAL_EDIT',

  THIRD_CATEGORY: 'THIRD_CATEGORY',
  THIRD_CATEGORY_CREATE: 'THIRD_CATEGORY_CREATE',
  THIRD_CATEGORY_DETAIL: 'THIRD_CATEGORY_DETAIL',
  THIRD_CATEGORY_EDIT: 'THIRD_CATEGORY_EDIT',

  TOPIC: 'TOPIC',
  TOPIC_CREATE: 'TOPIC_CREATE',
  TOPIC_DETAIL: 'TOPIC_DETAIL',
  TOPIC_EDIT: 'TOPIC_EDIT',

  PORT: 'PORT',
  PORT_CREATE: 'PORT_CREATE',
  PORT_EDIT: 'PORT_EDIT',
  PORT_DETAIL: 'PORT_DETAIL',

  CDI: 'CDI',
  CDI_CREATE: 'CDI_CREATE',
  CDI_DETAIL: 'CDI_DETAIL',
  CDI_EDIT: 'CDI_EDIT',

  SHORE_RANK: 'SHORE_RANK',
  SHORE_RANK_CREATE: 'SHORE_RANK_CREATE',
  SHORE_RANK_EDIT: 'SHORE_RANK_EDIT',
  SHORE_RANK_DETAIL: 'SHORE_RANK_DETAIL',

  SHORE_DEPARTMENT: 'SHORE_DEPARTMENT',
  SHORE_DEPARTMENT_CREATE: 'SHORE_DEPARTMENT_CREATE',
  SHORE_DEPARTMENT_EDIT: 'SHORE_DEPARTMENT_EDIT',
  SHORE_DEPARTMENT_DETAIL: 'SHORE_DEPARTMENT_DETAIL',

  AUDIT_CHECKLIST: 'AUDIT_CHECKLIST',
  AUDIT_CHECKLIST_CREATE: 'AUDIT_CHECKLIST_CREATE',
  AUDIT_CHECKLIST_EDIT: 'AUDIT_CHECKLIST_EDIT',
  AUDIT_CHECKLIST_DETAIL: 'AUDIT_CHECKLIST_DETAIL',

  PLANNING: 'PLANNING',
  PLANNING_AND_REQUEST_CREATE: 'PLANNING_AND_REQUEST_CREATE',
  PLANNING_AND_REQUEST_EDIT: 'PLANNING_AND_REQUEST_EDIT',
  PLANNING_AND_REQUEST_DETAIL: 'PLANNING_AND_REQUEST_DETAIL',

  REPORT_OF_FINDING: 'REPORT_OF_FINDING',
  REPORT_OF_FINDING_CREATE: 'REPORT_OF_FINDING_CREATE',
  REPORT_OF_FINDING_EDIT: 'REPORT_OF_FINDING_EDIT',
  REPORT_OF_FINDING_DETAIL: 'REPORT_OF_FINDING_DETAIL',

  REPORT_TEMPLATE: 'REPORT_TEMPLATE',
  REPORT_TEMPLATE_CREATE: 'REPORT_TEMPLATE_CREATE',
  REPORT_TEMPLATE_EDIT: 'REPORT_TEMPLATE_EDIT',
  REPORT_TEMPLATE_DETAIL: 'REPORT_TEMPLATE_DETAIL',

  SHIP_RANK: 'SHIP_RANK',
  SHIP_RANK_CREATE: 'SHIP_RANK_CREATE',
  SHIP_RANK_DETAIL: 'SHIP_RANK_DETAIL',
  SHIP_RANK_EDIT: 'SHIP_RANK_EDIT',

  VIQ: 'VIQ',
  VIQ_CREATE: 'VIQ_CREATE',
  VIQ_DETAIL: 'VIQ_DETAIL',
  VIQ_EDIT: 'VIQ_EDIT',

  DMS: 'DMS',
  DMS_CREATE: 'DMS_CREATE',
  DMS_DETAIL: 'DMS_DETAIL',
  DMS_EDIT: 'DMS_EDIT',

  PSC_DEFICIENCY: 'PSC_DEFICIENCY',
  PSC_DEFICIENCY_CREATE: 'PSC_DEFICIENCY_CREATE',
  PSC_DEFICIENCY_DETAIL: 'PSC_DEFICIENCY_DETAIL',
  PSC_DEFICIENCY_EDIT: 'PSC_DEFICIENCY_EDIT',

  INSPECTION_MAPPING: 'INSPECTION_MAPPING',
  INSPECTION_MAPPING_CREATE: 'INSPECTION_MAPPING_CREATE',
  INSPECTION_MAPPING_DETAIL: 'INSPECTION_MAPPING_DETAIL',
  INSPECTION_MAPPING_EDIT: 'INSPECTION_MAPPING_EDIT',

  MOBILE_CONFIG: 'MOBILE_CONFIG',

  AUDIT_INSPECTION_WORKSPACE: 'AUDIT_INSPECTION_WORKSPACE',
  AUDIT_INSPECTION_WORKSPACE_DETAIL: 'AUDIT_INSPECTION_WORKSPACE_DETAIL',
  AUDIT_INSPECTION_WORKSPACE_EDIT: 'AUDIT_INSPECTION_WORKSPACE_EDIT',

  INTERNAL_AUDIT_REPORT: 'INTERNAL_AUDIT_REPORT',
  INTERNAL_AUDIT_REPORT_CREATE: 'INTERNAL_AUDIT_REPORT_CREATE',
  INTERNAL_AUDIT_REPORT_DETAIL: 'INTERNAL_AUDIT_REPORT_DETAIL',
  INTERNAL_AUDIT_REPORT_EDIT: 'INTERNAL_AUDIT_REPORT_EDIT',

  DEPARTMENT_MASTER: 'DEPARTMENT_MASTER',
  DEPARTMENT_MASTER_CREATE: 'DEPARTMENT_MASTER_CREATE',
  DEPARTMENT_MASTER_DETAIL: 'DEPARTMENT_MASTER_DETAIL',
  DEPARTMENT_MASTER_EDIT: 'DEPARTMENT_MASTER_EDIT',

  RANK_MASTER: 'RANK_MASTER',
  RANK_MASTER_CREATE: 'RANK_MASTER_CREATE',
  RANK_MASTER_DETAIL: 'RANK_MASTER_DETAIL',
  RANK_MASTER_EDIT: 'RANK_MASTER_EDIT',

  NATURE_OF_FINDINGS_MASTER: 'NATURE_OF_FINDINGS_MASTER',
  NATURE_OF_FINDINGS_MASTER_CREATE: 'NATURE_OF_FINDINGS_MASTER_CREATE',
  NATURE_OF_FINDINGS_MASTER_DETAIL: 'NATURE_OF_FINDINGS_MASTER_DETAIL',
  NATURE_OF_FINDINGS_MASTER_EDIT: 'NATURE_OF_FINDINGS_MASTER_EDIT',

  WORK_FLOW: 'WORK_FLOW',
  WORK_FLOW_CREATE: 'WORK_FLOW_CREATE',
  WORK_FLOW_DETAIL: 'WORK_FLOW_DETAIL',
  WORK_FLOW_EDIT: 'WORK_FLOW_EDIT',

  DEVICE_CONTROL: 'DEVICE_CONTROL',

  APP_TYPE_PROPERTY: 'APP_TYPE_PROPERTY',
  APP_TYPE_PROPERTY_DETAIL: 'APP_TYPE_PROPERTY_DETAIL',
  APP_TYPE_PROPERTY_EDIT: 'APP_TYPE_PROPERTY_EDIT',

  CATEGORY_MAPPING: 'CATEGORY_MAPPING',
  CATEGORY_MAPPING_CREATE: 'CATEGORY_MAPPING_CREATE',
  CATEGORY_MAPPING_DETAIL: 'CATEGORY_MAPPING_DETAIL',
  CATEGORY_MAPPING_EDIT: 'CATEGORY_MAPPING_EDIT',

  FOCUS_REQUEST: 'FOCUS_REQUEST',
  FOCUS_REQUEST_CREATE: 'FOCUS_REQUEST_CREATE',
  FOCUS_REQUEST_DETAIL: 'FOCUS_REQUEST_DETAIL',
  FOCUS_REQUEST_EDIT: 'FOCUS_REQUEST_EDIT',

  INJURY_MASTER: 'INJURY_MASTER',
  INJURY_MASTER_CREATE: 'INJURY_MASTER_CREATE',
  INJURY_MASTER_DETAIL: 'INJURY_MASTER_DETAIL',
  INJURY_MASTER_EDIT: 'INJURY_MASTER_EDIT',

  INJURY_BODY: 'INJURY_BODY',
  INJURY_BODY_CREATE: 'INJURY_BODY_CREATE',
  INJURY_BODY_DETAIL: 'INJURY_BODY_DETAIL',
  INJURY_BODY_EDIT: 'INJURY_BODY_EDIT',

  INSPECTOR_TIME_OFF: 'INSPECTOR_TIME_OFF',
  INSPECTOR_TIME_OFF_CREATE: 'INSPECTOR_TIME_OFF_CREATE',
  INSPECTOR_TIME_OFF_DETAIL: 'INSPECTOR_TIME_OFF_DETAIL',
  INSPECTOR_TIME_OFF_EDIT: 'INSPECTOR_TIME_OFF_EDIT',

  INSPECTION_FOLLOW_UP: 'INSPECTION_FOLLOW_UP',
  INSPECTION_FOLLOW_UP_DETAIL: 'INSPECTION_FOLLOW_UP_DETAIL',
  INSPECTION_FOLLOW_UP_EDIT: 'INSPECTION_FOLLOW_UP_EDIT',

  FEATURE_CONFIG: 'FEATURE_CONFIG',

  QA_DASHBOARD: 'QA_DASHBOARD',

  STANDARD_MASTER: 'STANDARD_MASTER',
  STANDARD_MASTER_CREATE: 'STANDARD_MASTER_CREATE',
  STANDARD_MASTER_DETAIL: 'STANDARD_MASTER_DETAIL',
  STANDARD_MASTER_EDIT: 'STANDARD_MASTER_EDIT',

  SELF_ASSESSMENT: 'SELF_ASSESSMENT',
  SELF_ASSESSMENT_CREATE: 'SELF_ASSESSMENT_CREATE',
  SELF_ASSESSMENT_DETAIL: 'SELF_ASSESSMENT_DETAIL',
  SELF_ASSESSMENT_EDIT: 'SELF_ASSESSMENT_EDIT',

  ELEMENT_MASTER: 'ELEMENT_MASTER',
  ELEMENT_MASTER_CREATE: 'ELEMENT_MASTER_CREATE',
  ELEMENT_MASTER_DETAIL: 'ELEMENT_MASTER_DETAIL',
  ELEMENT_MASTER_EDIT: 'ELEMENT_MASTER_EDIT',

  EVENT_TYPE: 'EVENT_TYPE',
  EVENT_TYPE_CREATE: 'EVENT_TYPE_CREATE',
  EVENT_TYPE_DETAIL: 'EVENT_TYPE_DETAIL',
  EVENT_TYPE_EDIT: 'EVENT_TYPE_EDIT',

  INCIDENT_TYPE: 'INCIDENT_TYPE',
  INCIDENT_TYPE_CREATE: 'INCIDENT_TYPE_CREATE',
  INCIDENT_TYPE_DETAIL: 'INCIDENT_TYPE_DETAIL',
  INCIDENT_TYPE_EDIT: 'INCIDENT_TYPE_EDIT',

  SAIL_GENERAL_REPORT: 'SAIL_GENERAL_REPORT',
  SAIL_GENERAL_REPORT_CREATE: 'SAIL_GENERAL_REPORT_CREATE',
  SAIL_GENERAL_REPORT_DETAIL: 'SAIL_GENERAL_REPORT_DETAIL',
  SAIL_GENERAL_REPORT_EDIT: 'SAIL_GENERAL_REPORT_EDIT',

  SAIL_GENERAL_REPORT_INCIDENT: 'SAIL_GENERAL_REPORT_INCIDENT',
  SAIL_GENERAL_REPORT_INCIDENT_CREATE: 'SAIL_GENERAL_REPORT_INCIDENT_CREATE',
  SAIL_GENERAL_REPORT_INCIDENT_DETAIL: 'SAIL_GENERAL_REPORT_INCIDENT_DETAIL',
  SAIL_GENERAL_REPORT_INCIDENT_EDIT: 'SAIL_GENERAL_REPORT_INCIDENT_EDIT',

  SAIL_GENERAL_REPORT_PORT_STATE_CONTROL:
    'SAIL_GENERAL_REPORT_PORT_STATE_CONTROL',
  SAIL_GENERAL_REPORT_PORT_STATE_CONTROL_CREATE:
    'SAIL_GENERAL_REPORT_PORT_STATE_CONTROL_CREATE',
  SAIL_GENERAL_REPORT_PORT_STATE_CONTROL_DETAIL:
    'SAIL_GENERAL_REPORT_PORT_STATE_CONTROL_DETAIL',
  SAIL_GENERAL_REPORT_PORT_STATE_CONTROL_EDIT:
    'SAIL_GENERAL_REPORT_PORT_STATE_CONTROL_EDIT',

  SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS:
    'SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS',
  SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS_CREATE:
    'SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS_CREATE',
  SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS_DETAIL:
    'SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS_DETAIL',
  SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS_EDIT:
    'SAIL_GENERAL_REPORT_PORT_OTHER_INSPECTIONS_EDIT',

  SAIL_GENERAL_REPORT_INTERNAL_INSPECTIONS_AUDIT_CREATE:
    'SAIL_GENERAL_REPORT_INTERNAL_INSPECTIONS_AUDIT_CREATE',

  SAIL_GENERAL_REPORT_INTERNAL_INPECTIONS_AUDIT_EDIT:
    'SAIL_GENERAL_REPORT_INTERNAL_INPECTIONS_AUDIT_EDIT',
  SAIL_GENERAL_REPORT_INTERNAL_INPECTIONS_AUDIT_DETAIL:
    'SAIL_GENERAL_REPORT_INTERNAL_INPECTIONS_AUDIT_DETAIL',

  ISSUE_NOTE: 'ISSUE_NOTE',
  ISSUE_NOTE_CREATE: 'ISSUE_NOTE_CREATE',
  ISSUE_NOTE_DETAIL: 'ISSUE_NOTE_DETAIL',
  ISSUE_NOTE_EDIT: 'ISSUE_NOTE_EDIT',

  TRANSFER_TYPE: 'TRANSFER_TYPE',
  TRANSFER_TYPE_CREATE: 'TRANSFER_TYPE_CREATE',
  TRANSFER_TYPE_DETAIL: 'TRANSFER_TYPE_DETAIL',
  TRANSFER_TYPE_EDIT: 'TRANSFER_TYPE_EDIT',

  CARGO: 'CARGO',
  CARGO_CREATE: 'CARGO_CREATE',
  CARGO_DETAIL: 'CARGO_DETAIL',
  CARGO_EDIT: 'CARGO_EDIT',

  REPEATED_FINDING: 'REPEATED_FINDING',
  REPEATED_FINDING_CREATE: 'REPEATED_FINDING_CREATE',
  REPEATED_FINDING_DETAIL: 'REPEATED_FINDING_DETAIL',
  REPEATED_FINDING_EDIT: 'REPEATED_FINDING_EDIT',

  CARGO_TYPE: 'CARGO_TYPE',
  CARGO_TYPE_CREATE: 'CARGO_TYPE_CREATE',
  CARGO_TYPE_DETAIL: 'CARGO_TYPE_DETAIL',
  CARGO_TYPE_EDIT: 'CARGO_TYPE_EDIT',

  VESSEL_SCREENING: 'VESSEL_SCREENING',
  VESSEL_SCREENING_CREATE: 'VESSEL_SCREENING_CREATE',
  VESSEL_SCREENING_DETAIL: 'VESSEL_SCREENING_DETAIL',
  VESSEL_SCREENING_EDIT: 'VESSEL_SCREENING_EDIT',

  INCIDENTS: 'INCIDENTS',
  INCIDENTS_CREATE: 'INCIDENTS_CREATE',
  INCIDENTS_DETAIL: 'INCIDENTS_DETAIL',
  INCIDENTS_EDIT: 'INCIDENTS_EDIT',

  PILOT_TERMINAL_FEEDBACK: 'PILOT_TERMINAL_FEEDBACK',
  PILOT_TERMINAL_FEEDBACK_CREATE: 'PILOT_TERMINAL_FEEDBACK_CREATE',
  PILOT_TERMINAL_FEEDBACK_DETAIL: 'PILOT_TERMINAL_FEEDBACK_DETAIL',
  PILOT_TERMINAL_FEEDBACK_EDIT: 'PILOT_TERMINAL_FEEDBACK_EDIT',

  CREW_GROUPING: 'CREW_GROUPING',
  CREW_GROUPING_CREATE: 'CREW_GROUPING_CREATE',
  CREW_GROUPING_DETAIL: 'CREW_GROUPING_DETAIL',
  CREW_GROUPING_EDIT: 'CREW_GROUPING_EDIT',

  COUNTRY: 'COUNTRY',
  MODULE_CONFIGURATION: 'MODULE_CONFIGURATION',
  MODULE_CONFIGURATION_VIEW: 'MODULE_CONFIGURATION_VIEW',
  MODULE_CONFIGURATION_EDIT: 'MODULE_CONFIGURATION_EDIT',

  MY_WATCHLIST: 'MY_WATCHLIST',
};
