import { ModuleConfigurationModelStore } from 'models/store/module-configuration/module-configuration.model';
import { SurveyClassInfoStoreModel } from 'models/store/survey-class-info/survey-class-info.model';

// START_NEW_PAGE
import { ValueManagementStoreModel } from 'pages/value-management/utils/model';
// END_NEW_PAGE
import { CompanyTypeStore } from 'pages/company-type/utils/model';
import { SelfAssessmentStoreModel } from 'pages/self-assessment/utils/model';
import { TransferTypeStoreModel } from 'pages/transfer-type/utils/model';
import { CargoStoreModel } from 'pages/cargo/utils/model';
import { PlanDrawingStoreModel } from 'pages/plan-drawing/utils/model';
import { MapViewStore } from 'pages/map-view/utils/model';
import { DivisionStore } from 'pages/division/utils/model';
import { DivisionMappingStore } from 'pages/division-mapping/utils/model';
import {
  VesselScreeningStoreModel,
  VesselMaintenanceStoreModel,
  VesselOtherTechRecordsStoreModel,
  VesselDryDockingStoreModel,
  VesselIncidentInvestigationStoreModel,
  VesselPortStateControlStoreModel,
} from 'pages/vessel-screening/utils/models/common.model';
import { RepeateFindingCalculationStoreModel } from 'pages/repeated-finding/utils/model';
import { VesselSurveysClassInfoStoreModel } from 'pages/vessel-screening/utils/models/vessel-surveys-class-info.model';
import { IncidentStoreModel } from 'pages/incidents/utils/models/common.model';
import { VesselClassDispensationsStoreModel } from 'pages/vessel-screening/utils/models/vessel-class-dispensations.model';
import { CargoTypeStoreModel } from 'pages/cargo-type/utils/model';
import { VesselInternalInspectionStoreModel } from 'pages/vessel-screening/utils/models/internal-inspection.model';
import { VesselExternalInspectionStoreModel } from 'pages/vessel-screening/utils/models/external-inspection.model';
import { VesselOtherSMSStoreModel } from 'pages/vessel-screening/utils/models/other-sms.model';
import { VesselPlanAndDrawingStoreModel } from 'pages/vessel-screening/utils/models/plan-and-drawing.model';
import { SailReportingSummaryStoreModel } from 'models/api/summary-sail-reporting/summary-sail-reporting.model';
import { VesselSummaryStoreModel } from 'pages/vessel-screening/utils/models/summary.model';
import { PilotTerminalFeedbackStoreModel } from 'pages/pilot-terminal-feedback/utils/models/common.model';
import { CrewGroupingStoreModel } from 'pages/crew-grouping/utils/model';
import { NotificationStore } from 'pages/notification/utils/model';
import { VoyageInfoStoreModel } from 'pages/vessel-screening/utils/models/voyage-info.model';
import { CountryMasterStoreModel } from 'models/api/country-master/country-master.model';
import { VesselInjuriesSafetyStoreModel } from '../../pages/vessel-screening/utils/models/injuries-safety.model';
import { AuthenticateStoreModel } from './authenticate.model';
import { AuditCheckListStore } from './audit-checklist/audit-checklist.model';
import { RoleAndPermissionStoreModel } from './role/role.model';
import { UserManagementState } from './user/user.model';
import { VesselTypeState } from './vessel-type/vessel-type.model';
import { AuthorityMasterState } from './authority-master/authority-master.model';
import { AuditTypeStoreModel } from './audit-type/audit-type.model';
import { FleetStoreModel } from './fleet/fleet.model';
import { CDIStoreModel } from './cdi/cdi.model';
import { ReportTemplateStoreModel } from './report-template/report-template.model';
import { VIQStoreModel } from './viq/viq.model';
import { GroupManagementStore } from './group/group.model';
import { CompanyManagementState } from './company/company.model';
import { CharterOwnerStoreModel } from './charter-owner/charter-owner.model';
import { AuditTimeTableStoreModel } from './audit-time-table/audit-time-table.model';
import { PscActionStoreModel } from './psc-action/psc-action.model';
import { OwnerBusinessStoreModel } from './owner-business/owner-business.model';
import { LocationStoreModel } from './location/location.model';
import { ShipDirectResponsibleStoreModel } from './ship-direct-responsible/ship-direct-responsible.model';
import { ShipDepartmentStoreModel } from './ship-department/ship-department.model';
import { CategoryStoreModel } from './category/category.model';
import { TopicStoreModel } from './topic/topic.model';
import { MailManagementStoreModel } from './mail-management/mail-management.model';
import { VesselManagementState } from './vessel/vessel.model';
import { ShoreDepartmentStore } from './shore-department/shore-department.models';
import { ShoreRankState } from './shore-rank/shore-rank.model';
import { PortState } from './port/port.model';
import { ShipRankStoreModel } from './ship-rank/ship-rank.model';
import { DMSStoreModel } from './dms/dms.model';
import { MainCategoryStoreModel } from './main-category/main-category.model';
import { ReportOfFindingStore } from './report-of-finding/report-of-finding.model';
import { SecondCategoryStoreModel } from './second-category/second-category.model';
import { RiskFactorStoreModel } from './risk-factor/risk-factor.model';
import { ExternalStoreModel } from './external/external.model';
import { TerminalStoreModel } from './terminal/terminal.model';
import { ThirdCategoryStoreModel } from './third-category/third-category.model';
import { InspectionMappingStoreModel } from './inspection-mapping/inspection-mapping.model';
import { PSCDeficiencyState } from './psc-deficiency/psc-deficiency.model';
import { AuditInspectionWorkspaceStoreModel } from './audit-inspection-workspace/audit-inspection-workspace.model';
import { PlanningAndRequestStore } from './planning-and-request/planning-and-request.model';
import { PortStateControlStoreModel } from './port-state-control/port-state-control.model';

import { InternalAuditReportStoreModel } from './internal-audit-report/internal-audit-report.model';
import { DepartmentMasterState } from './department-master/department-master.model';
import { RankMasterState } from './rank-master/rank-master.model';
import { AttachmentKitStoreModel } from './attachment-kit/attachment-kit.model';
import { NatureOfFindingsMasterState } from './nature-of-findings-master/nature-of-findings-master.model';
import { WorkFlowState } from './work-flow/work-flow.model';
import { DashboardStoreModel } from './dashboard/dashboard.model';
import { DeviceControlState } from './device-control/device-control.model';
import { AppTypePropertyState } from './app-type-property/app-type-property.model';
import { CategoryMappingStoreModel } from './category-mapping/category-mapping.model';
import { TemplateState } from './template/template.model';
import { FocusRequestStoreModel } from './focus-request/focus-request.model';
import { InspectorTimeOffStoreModel } from './inspector-time-off/inspector-time-off.model';
import { FeatureConfigStoreModel } from './feature-config/feature-config.model';
import { StandardMasterStoreModel } from './standard-master/standard-master.model';
import { ElementMasterStoreModel } from './element-master/element-master.model';
import { InspectionFollowUpStoreModel } from './inspection-follow-up/inspection-follow-up.model';
import { EventTypeStoreModel } from './event-type/event-type.model';
import { IncidentTypeStoreModel } from './incident-type/incident-type.model';
import { IssueNoteStoreModel } from './issue-note/issue-note.model';
import { ConditionOfClassStoreModel } from './condition-of-class/condition-of-class.model';
import { IncidentInvestigationStoreModel } from './incident-investigation/incident-investigation.model';
import { DryDockingStoreModel } from './dry-docking/dry-docking.model';
import { MaintenanceTechnicalStoreModel } from './maintenance-performance/maintenance-performance.model';
import { OtherTechnicalRecordsStoreModel } from './other-technical-records/other-technical-records.model';
import { InjuryStoreModel } from './injury/injury.model';
import { InjuryMasterStoreModel } from './injury-master/injury-master.model';
import { InjuryBodyStoreModel } from './injury-body/injury-body.model';
import { PlanningAndDrawingsStoreModel } from './plans-and-drawings/plans-and-drawings.model';
import { SmsStoreModel } from './sms/sms.model';
import { SailReportInspectionInternalModel } from './sail-report-inspection-internal/sail-report-inspection-internal.model';
import { HomePageStoreModel } from './home-page/home-page.model';
import { DynamicStoreModel } from './dynamic/dynamic.model';
import { WatchListStoreModel } from './watch-list/watch-list.model';

export interface StoreState {
  authenticate: AuthenticateStoreModel;
  roleAndPermission: RoleAndPermissionStoreModel;
  user: UserManagementState;
  vesselType: VesselTypeState;
  authorityMaster: AuthorityMasterState;
  auditType: AuditTypeStoreModel;
  fleet: FleetStoreModel;
  group: GroupManagementStore;
  companyManagement: CompanyManagementState;
  vessel: VesselManagementState;
  charterOwner: CharterOwnerStoreModel;
  auditTimeTable: AuditTimeTableStoreModel;
  pscAction: PscActionStoreModel;
  ownerBusiness: OwnerBusinessStoreModel;
  shipDepartment: ShipDepartmentStoreModel;
  shipDirectResponsible: ShipDirectResponsibleStoreModel;
  category: CategoryStoreModel;
  mainCategory: MainCategoryStoreModel;
  reportOfFinding: ReportOfFindingStore;
  secondCategory: SecondCategoryStoreModel;
  riskFactor: RiskFactorStoreModel;
  thirdCategory: ThirdCategoryStoreModel;
  terminal: TerminalStoreModel;
  topic: TopicStoreModel;
  location: LocationStoreModel;
  mailManagement: MailManagementStoreModel;
  shoreRank: ShoreRankState;
  shoreDepartment: ShoreDepartmentStore;
  auditCheckList: AuditCheckListStore;
  cdi: CDIStoreModel;
  ReportTemplate: ReportTemplateStoreModel;
  port: PortState;
  shipRank: ShipRankStoreModel;
  viq: VIQStoreModel;
  dms: DMSStoreModel;
  inspectionMapping: InspectionMappingStoreModel;
  pscDeficiency: PSCDeficiencyState;
  attachmentKit: AttachmentKitStoreModel;
  auditInspectionWorkspace: AuditInspectionWorkspaceStoreModel;
  planningAndRequest: PlanningAndRequestStore;
  internalAuditReport: InternalAuditReportStoreModel;
  departmentMaster: DepartmentMasterState;
  rankMaster: RankMasterState;
  natureOfFindingsMaster: NatureOfFindingsMasterState;
  workFlow: WorkFlowState;
  dashboard: DashboardStoreModel;
  deviceControl: DeviceControlState;
  appTypeProperty: AppTypePropertyState;
  categoryMapping: CategoryMappingStoreModel;
  template: TemplateState;
  focusRequest: FocusRequestStoreModel;
  inspectorTimeOff: InspectorTimeOffStoreModel;
  inspectionFollowUp: InspectionFollowUpStoreModel;
  featureConfig: FeatureConfigStoreModel;
  standardMaster: StandardMasterStoreModel;
  surveyClassInfo: SurveyClassInfoStoreModel;
  dryDocking: DryDockingStoreModel;
  external: ExternalStoreModel;
  selfAssessment: SelfAssessmentStoreModel;
  elementMaster: ElementMasterStoreModel;
  eventType: EventTypeStoreModel;
  incidentType: IncidentTypeStoreModel;
  issueNote: IssueNoteStoreModel;
  conditionOfClass: ConditionOfClassStoreModel;
  incidentInvestigation: IncidentInvestigationStoreModel;
  maintenancePerformance: MaintenanceTechnicalStoreModel;
  otherTechnicalRecords: OtherTechnicalRecordsStoreModel;
  injury: InjuryStoreModel;
  planningAndDrawings: PlanningAndDrawingsStoreModel;
  injuryMaster: InjuryMasterStoreModel;
  injuryBody: InjuryBodyStoreModel;
  plansAndDrawing: PlanningAndDrawingsStoreModel;
  smsRecord: SmsStoreModel;
  // START_NEW_PAGE
  valueManagement: ValueManagementStoreModel;
  // END_NEW_PAGE
  companyType: CompanyTypeStore;
  portStateControl: PortStateControlStoreModel;
  sailReportInspectionInternal: SailReportInspectionInternalModel;
  transferType: TransferTypeStoreModel;
  cargo: CargoStoreModel;
  cargoType: CargoTypeStoreModel;
  vesselScreening: VesselScreeningStoreModel;
  vesselIncidentInvestigation: VesselIncidentInvestigationStoreModel;
  vesselMaintenancePerformance: VesselMaintenanceStoreModel;
  vesselOtherTechRecords: VesselOtherTechRecordsStoreModel;
  vesselInternalInspection: VesselInternalInspectionStoreModel;
  vesselExternalInspection: VesselExternalInspectionStoreModel;
  vesselPortStateControl: VesselPortStateControlStoreModel;
  vesselSurveysClassInfo: VesselSurveysClassInfoStoreModel;
  vesselDryDocking: VesselDryDockingStoreModel;
  vesselInjuriesSafety: VesselInjuriesSafetyStoreModel;
  vesselClassDispensations: VesselClassDispensationsStoreModel;
  vesselOtherSMS: VesselOtherSMSStoreModel;
  vesselPlanAndDrawing: VesselPlanAndDrawingStoreModel;
  incidents: IncidentStoreModel;
  sailReportingSummary: SailReportingSummaryStoreModel;
  vesselSummary: VesselSummaryStoreModel;
  planDrawing: PlanDrawingStoreModel;
  mapView?: MapViewStore;
  pilotTerminalFeedback: PilotTerminalFeedbackStoreModel;
  crewGrouping: CrewGroupingStoreModel;
  division?: DivisionStore;
  divisionMapping: DivisionMappingStore;
  notification: NotificationStore;
  repeatedFindingCal: RepeateFindingCalculationStoreModel;
  voyageInfo: VoyageInfoStoreModel;
  countryMaster: CountryMasterStoreModel;
  homepage: HomePageStoreModel;
  moduleConfiguration: ModuleConfigurationModelStore;
  dynamic: DynamicStoreModel;
  watchList: WatchListStoreModel;
}
